# Generated by Django 5.2.17 on 2026-09-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_active_name_index"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="product",
            new_name="catalog_prod_active_name_idx",
            old_name="catalog_product_active_name_idx",
        ),
    ]
