# Generated by Django 5.2.17 on 2026-09-25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("catalog", "0005_rename_product_active_name_index")]

    operations = [
        migrations.CreateModel(
            name="SkuSequence",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(default="GLOBAL", max_length=32, unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
