# Generated by Django 5.2.17 on 2026-10-02

from django.db import migrations, models


def copy_existing_purchase_prices(apps, schema_editor):
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    VariantInventoryCost = apps.get_model("inventory", "VariantInventoryCost")
    costs_by_variant = {
        cost.variant_id: cost.weighted_average_unit_cost
        for cost in VariantInventoryCost.objects.exclude(weighted_average_unit_cost=0)
    }
    for variant in ProductVariant.objects.filter(purchase_price__isnull=True):
        if variant.id in costs_by_variant:
            variant.purchase_price = costs_by_variant[variant.id]
            variant.save(update_fields=("purchase_price",))


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_skusequence"),
        ("inventory", "0004_stockbalance_location_quantity_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="purchase_price",
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.RunPython(copy_existing_purchase_prices, migrations.RunPython.noop),
    ]
