# Generated by Django 5.2.17 on 2026-09-01 22:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('STOCK_DEPLETED', 'Articolo esaurito'), ('REORDER', 'Riordino'), ('VOUCHER_EXPIRING', 'Buono in scadenza'), ('EXPENSE_DUE', 'Scadenza spesa'), ('GIFT_LIST', 'Lista regalo'), ('SYSTEM', 'Sistema')], max_length=24)),
                ('priority', models.CharField(choices=[('LOW', 'Bassa'), ('NORMAL', 'Normale'), ('HIGH', 'Alta'), ('CRITICAL', 'Critica')], default='NORMAL', max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'Attiva'), ('RESOLVED', 'Risolta')], default='ACTIVE', max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('message', models.TextField()),
                ('deduplication_key', models.CharField(max_length=180)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('action_path', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.CharField(blank=True, max_length=255)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_role_codes', models.JSONField(default=list)),
                ('delivered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-delivered_at',),
            },
        ),
        migrations.CreateModel(
            name='NotificationResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(max_length=255)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resolution', to='notifications.notification')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_resolution_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'priority', 'occurred_at'], name='notif_status_priority_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['source_type', 'source_id'], name='notif_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('deduplication_key',), name='notif_active_dedupe_unique'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_id__isnull', True), ('source_type', '')), models.Q(models.Q(('source_type', ''), _negated=True), ('source_id__isnull', False)), _connector='OR'), name='notif_source_pair_valid'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'RESOLVED'), _negated=True), models.Q(('resolved_at__isnull', False), ('resolved_by__isnull', False)), _connector='OR'), name='notif_resolved_audit'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'user'), name='notif_delivery_user_unique'),
        ),
    ]
