FROM node:22-alpine AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL=/api/v1
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

FROM nginx:1.27-alpine

COPY docker-entrypoint.production.sh /usr/local/bin/diavoletti-entrypoint
COPY nginx /etc/nginx/diavoletti
COPY --from=build /app/dist /usr/share/nginx/html

RUN chmod +x /usr/local/bin/diavoletti-entrypoint

EXPOSE 80
EXPOSE 443

ENTRYPOINT ["/usr/local/bin/diavoletti-entrypoint"]
CMD ["nginx", "-g", "daemon off;"]
