# Generated by Django 5.2.17 on 2026-08-30 20:07

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_productvariant_productbarcode_and_more'),
        ('core', '0002_seed_initial_data'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('order_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('SENT', 'Inviato'), ('PARTIALLY_RECEIVED', 'Parzialmente ricevuto'), ('RECEIVED', 'Ricevuto'), ('CANCELLED', 'Annullato')], default='DRAFT', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'ordering': ('-order_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=32, unique=True)),
                ('delivery_note_number', models.CharField(blank=True, max_length=64)),
                ('delivery_note_date', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('CONFIRMED', 'Confermata'), ('CANCELLED', 'Annullata')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='core.location')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='suppliers.supplier')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='purchasing.purchaseorder')),
            ],
            options={
                'ordering': ('-received_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_product_code', models.CharField(blank=True, max_length=80)),
                ('quantity_ordered', models.PositiveIntegerField()),
                ('expected_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_received', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('final_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.goodsreceipt')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='catalog.productvariant')),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_lines', to='purchasing.purchaseorderline')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=64)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('CONFIRMED', 'Confermata'), ('CANCELLED', 'Annullata')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_invoices', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='suppliers.supplier')),
            ],
            options={
                'ordering': ('-invoice_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_invoiced', models.PositiveIntegerField()),
                ('final_unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.supplierinvoice')),
                ('receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='purchasing.goodsreceiptline')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_invoice_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='PurchaseCostAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_invoiced', models.PositiveIntegerField()),
                ('previous_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('final_unit_cost', models.DecimalField(decimal_places=4, max_digits=14)),
                ('total_cost_delta', models.DecimalField(decimal_places=2, max_digits=16)),
                ('remaining_quantity_affected', models.PositiveIntegerField(default=0)),
                ('inventory_value_delta', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('sold_quantity_affected', models.PositiveIntegerField(default=0)),
                ('sold_cost_delta', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_cost_adjustments', to='catalog.productvariant')),
                ('invoice_line', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cost_adjustment', to='purchasing.supplierinvoiceline')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupplierInvoiceReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_links', to='purchasing.supplierinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_links', to='purchasing.goodsreceipt')),
            ],
        ),
        migrations.AddField(
            model_name='supplierinvoice',
            name='receipts',
            field=models.ManyToManyField(blank=True, related_name='supplier_invoices', through='purchasing.SupplierInvoiceReceipt', to='purchasing.goodsreceipt'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('expected_delivery_date__isnull', True), ('expected_delivery_date__gte', models.F('order_date')), _connector='OR'), name='purchasing_order_delivery_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('order', 'variant'), name='purchasing_order_variant_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_ordered__gt', 0)), name='purchasing_order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_unit_cost__isnull', True), ('expected_unit_cost__gte', 0), _connector='OR'), name='purchasing_expected_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.UniqueConstraint(fields=('receipt', 'variant'), name='purchasing_receipt_variant_unique'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gt', 0)), name='purchasing_received_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='purchasing_receipt_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('final_sale_price__isnull', True), ('final_sale_price__gt', 0), _connector='OR'), name='purchasing_final_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_invoiced__gt', 0)), name='purch_inv_line_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('final_unit_cost__gte', 0)), name='purch_inv_line_cost_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_percentage__gte', 0), ('tax_percentage__lte', 100)), name='purch_inv_line_tax_valid'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amount__gte', 0), ('tax_amount__gte', 0), ('total_amount__gte', 0)), name='purch_inv_line_totals_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('taxable_amount'), '+', models.F('tax_amount')))), name='purch_inv_line_total_match'),
        ),
        migrations.AddConstraint(
            model_name='purchasecostadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_invoiced__gt', 0)), name='purch_cost_adj_qty_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchasecostadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('previous_unit_cost__isnull', True), ('previous_unit_cost__gte', 0), _connector='OR'), name='purch_cost_adj_previous_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchasecostadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('final_unit_cost__gte', 0)), name='purch_cost_adj_final_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchasecostadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('remaining_quantity_affected__lte', django.db.models.expressions.CombinedExpression(models.F('quantity_invoiced'), '-', models.F('sold_quantity_affected')))), name='purch_cost_adj_split_valid'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoicereceipt',
            constraint=models.UniqueConstraint(fields=('invoice', 'receipt'), name='purchasing_invoice_receipt_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.UniqueConstraint(fields=('supplier', 'invoice_number'), name='purchasing_supplier_invoice_unique'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', models.F('invoice_date')), _connector='OR'), name='purchasing_invoice_due_date_valid'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amount__gte', 0), ('tax_amount__gte', 0), ('total_amount__gte', 0)), name='purchasing_invoice_totals_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='supplierinvoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('taxable_amount'), '+', models.F('tax_amount')))), name='purchasing_invoice_total_matches'),
        ),
    ]
