# Generated by Django 5.2.17 on 2026-09-01 22:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_shopsettings_voucher_validity_months'),
        ('customers', '0001_initial'),
        ('sales', '0003_salenumbersequence'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReturnNumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('CONFIRMED', 'Confermato'), ('CANCELLED', 'Annullato')], default='DRAFT', max_length=16)),
                ('reason', models.CharField(max_length=255)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('points_reversed', models.PositiveIntegerField(default=0)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_customer_returns', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_customer_returns', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_customer_returns', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='customers.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_returns', to='core.location')),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_returns', to='sales.sale')),
                ('return_voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_customer_return', to='vouchers.voucher')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CustomerReturnLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('restock', models.BooleanField(default=True)),
                ('unit_refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sku_snapshot', models.CharField(max_length=64)),
                ('product_name_snapshot', models.CharField(max_length=160)),
                ('customer_return', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='returns.customerreturn')),
                ('original_sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='sales.saleline')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='customerreturn',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('number',), name='return_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='customerreturn',
            constraint=models.CheckConstraint(condition=models.Q(('total_refund_amount__gte', 0)), name='return_refund_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerreturn',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMED'), _negated=True), models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('number__gt', ''), ('return_voucher__isnull', False), ('total_refund_amount__gt', 0)), _connector='OR'), name='return_confirmed_audit'),
        ),
        migrations.AddConstraint(
            model_name='customerreturnline',
            constraint=models.UniqueConstraint(fields=('customer_return', 'original_sale_line'), name='return_line_sale_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='customerreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='return_line_quantity_pos'),
        ),
        migrations.AddConstraint(
            model_name='customerreturnline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_refund_amount__gte', 0), ('total_refund_amount__gt', 0)), name='return_line_amounts_valid'),
        ),
    ]
