# Generated by Django 5.2.17 on 2026-09-01 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_shopsettings_voucher_validity_months'),
        ('sales', '0003_salenumbersequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('provider', models.CharField(choices=[('SHOPIFY', 'Shopify')], max_length=24)),
                ('shop_domain', models.CharField(blank=True, max_length=255)),
                ('api_version', models.CharField(default='2026-07', max_length=16)),
                ('credentials_env_prefix', models.CharField(default='SHOPIFY', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('default_sale_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_sale_integrations', to='core.location')),
                ('online_locations', models.ManyToManyField(blank=True, related_name='integration_connections', to='core.location')),
                ('system_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ImportedOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=128)),
                ('order_number', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('RECEIVED', 'Ricevuto'), ('WAITING_PAYMENT', 'In attesa di pagamento'), ('IMPORTED', 'Importato'), ('BLOCKED', 'Bloccato'), ('CANCELLED', 'Annullato')], default='RECEIVED', max_length=24)),
                ('financial_status', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imported_external_order', to='sales.sale')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='integrations.integrationconnection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_id'), name='int_imported_order_unique')],
            },
        ),
        migrations.CreateModel(
            name='ExternalObjectMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.CharField(choices=[('PRODUCT', 'Prodotto'), ('VARIANT', 'Variante'), ('CUSTOMER', 'Cliente'), ('ORDER', 'Ordine')], max_length=24)),
                ('internal_id', models.UUIDField()),
                ('external_id', models.CharField(max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations.integrationconnection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'object_type', 'internal_id'), name='int_map_internal_unique'), models.UniqueConstraint(fields=('connection', 'object_type', 'external_id'), name='int_map_external_unique')],
            },
        ),
        migrations.CreateModel(
            name='SyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('INVENTORY', 'Giacenza'), ('PRODUCT', 'Prodotto'), ('ORDER', 'Ordine')], max_length=24)),
                ('deduplication_key', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('PROCESSING', 'In elaborazione'), ('RETRY', 'Da riprovare'), ('SUCCEEDED', 'Completato'), ('FAILED', 'Fallito')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('available_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='integrations.integrationconnection')),
            ],
            options={
                'ordering': ('available_at', 'created_at'),
                'indexes': [models.Index(fields=['status', 'available_at'], name='int_sync_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ('PENDING', 'PROCESSING', 'RETRY'))), fields=('connection', 'deduplication_key'), name='int_sync_open_dedupe_unique')],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_event_id', models.CharField(max_length=128)),
                ('topic', models.CharField(max_length=96)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('RECEIVED', 'Ricevuto'), ('PROCESSED', 'Elaborato'), ('FAILED', 'Fallito')], default='RECEIVED', max_length=16)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='integrations.integrationconnection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('connection', 'external_event_id'), name='int_webhook_event_unique')],
            },
        ),
    ]
