# Generated by Django 5.2.17 on 2026-09-01 19:34

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_productvariant_productbarcode_and_more'),
        ('sales', '0003_salenumbersequence'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('campaign_type', models.CharField(choices=[('SALE', 'Saldi'), ('PROMOTION', 'Promozione')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('ACTIVE', 'Attiva'), ('ENDED', 'Terminata'), ('CANCELLED', 'Annullata')], default='DRAFT', max_length=16)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_promotion_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-valid_from', 'name'),
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('rule_type', models.CharField(choices=[('PERCENTAGE', 'Sconto percentuale'), ('FIXED_DISCOUNT', 'Sconto fisso'), ('FIXED_PRICE', 'Prezzo fisso'), ('CHEAPEST_PERCENTAGE', 'Meno caro con sconto percentuale'), ('GROUP_FIXED_PRICE', 'Articolo del gruppo a prezzo fisso')], max_length=32)),
                ('required_quantity', models.PositiveIntegerField(default=1)),
                ('discounted_quantity', models.PositiveIntegerField(default=1)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fixed_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fixed_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('repeatable', models.BooleanField(default=False)),
                ('grouping_mode', models.CharField(choices=[('ANY_ELIGIBLE', 'Qualsiasi articolo idoneo'), ('SAME_PRODUCT', 'Stesso prodotto'), ('SAME_VARIANT', 'Stessa variante'), ('SAME_CATEGORY', 'Stessa categoria'), ('SAME_BRAND', 'Stessa marca')], default='ANY_ELIGIBLE', max_length=24)),
                ('target_selection', models.CharField(choices=[('ALL', 'Tutti gli articoli'), ('CHEAPEST', 'Articolo meno caro'), ('MOST_EXPENSIVE', 'Articolo più caro'), ('OPERATOR_SELECTED', "Scelto dall'operatore")], default='ALL', max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('required_quantity__gt', 0)), name='promo_rule_required_qty_positive'), models.CheckConstraint(condition=models.Q(('discounted_quantity__gt', 0), ('discounted_quantity__lte', models.F('required_quantity'))), name='promo_rule_discounted_qty_valid'), models.CheckConstraint(condition=models.Q(('discount_percentage__isnull', True), models.Q(('discount_percentage__gt', Decimal('0.00')), ('discount_percentage__lte', Decimal('100.00'))), _connector='OR'), name='promo_rule_percentage_valid'), models.CheckConstraint(condition=models.Q(('fixed_discount_amount__isnull', True), ('fixed_discount_amount__gt', Decimal('0.00')), _connector='OR'), name='promo_rule_fixed_discount_valid'), models.CheckConstraint(condition=models.Q(('fixed_unit_price__isnull', True), ('fixed_unit_price__gte', Decimal('0.00')), _connector='OR'), name='promo_rule_fixed_price_valid')],
            },
        ),
        migrations.CreateModel(
            name='CampaignOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48)),
                ('name', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_campaign_offers', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='promotions.promotioncampaign')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_offers', to='promotions.promotionrule')),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='SalePromotionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('APPLIED', 'Applicata'), ('REMOVED', 'Rimossa')], default='APPLIED', max_length=16)),
                ('campaign_code_snapshot', models.CharField(max_length=48)),
                ('campaign_name_snapshot', models.CharField(max_length=160)),
                ('campaign_type_snapshot', models.CharField(max_length=16)),
                ('offer_code_snapshot', models.CharField(max_length=48)),
                ('offer_name_snapshot', models.CharField(max_length=160)),
                ('rule_code_snapshot', models.CharField(max_length=48)),
                ('rule_name_snapshot', models.CharField(max_length=160)),
                ('rule_type_snapshot', models.CharField(max_length=32)),
                ('rule_parameters_snapshot', models.JSONField(default=dict)),
                ('scope_snapshot', models.JSONField(default=dict)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.CharField(blank=True, max_length=255)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applied_sale_promotions', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_applications', to='promotions.campaignoffer')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_sale_promotions', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_applications', to='sales.sale')),
            ],
            options={
                'ordering': ('applied_at',),
            },
        ),
        migrations.CreateModel(
            name='SalePromotionAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_number', models.PositiveIntegerField(default=1)),
                ('quantity_in_group', models.PositiveIntegerField()),
                ('discounted_quantity', models.PositiveIntegerField(default=0)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_allocations', to='sales.saleline')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='promotions.salepromotionapplication')),
            ],
            options={
                'ordering': ('application', 'group_number', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='OfferBrandScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('INCLUDE', 'Includi'), ('EXCLUDE', 'Escludi')], max_length=8)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_offer_scopes', to='catalog.brand')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_scopes', to='promotions.campaignoffer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('offer', 'brand'), name='promo_offer_brand_unique')],
            },
        ),
        migrations.CreateModel(
            name='OfferCategoryScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('INCLUDE', 'Includi'), ('EXCLUDE', 'Escludi')], max_length=8)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_offer_scopes', to='catalog.category')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_scopes', to='promotions.campaignoffer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('offer', 'category'), name='promo_offer_category_unique')],
            },
        ),
        migrations.CreateModel(
            name='OfferProductScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('INCLUDE', 'Includi'), ('EXCLUDE', 'Escludi')], max_length=8)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_scopes', to='promotions.campaignoffer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_offer_scopes', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('offer', 'product'), name='promo_offer_product_unique')],
            },
        ),
        migrations.CreateModel(
            name='OfferSeasonScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('INCLUDE', 'Includi'), ('EXCLUDE', 'Escludi')], max_length=8)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_scopes', to='promotions.campaignoffer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_offer_scopes', to='catalog.season')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('offer', 'season'), name='promo_offer_season_unique')],
            },
        ),
        migrations.CreateModel(
            name='OfferSupplierScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('INCLUDE', 'Includi'), ('EXCLUDE', 'Escludi')], max_length=8)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_scopes', to='promotions.campaignoffer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_offer_scopes', to='suppliers.supplier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('offer', 'supplier'), name='promo_offer_supplier_unique')],
            },
        ),
        migrations.CreateModel(
            name='OfferVariantScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('INCLUDE', 'Includi'), ('EXCLUDE', 'Escludi')], max_length=8)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_scopes', to='promotions.campaignoffer')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_offer_scopes', to='catalog.productvariant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('offer', 'variant'), name='promo_offer_variant_unique')],
            },
        ),
        migrations.AddConstraint(
            model_name='promotioncampaign',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__gt', models.F('valid_from'))), name='promo_campaign_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='campaignoffer',
            constraint=models.UniqueConstraint(fields=('campaign', 'code'), name='promo_offer_campaign_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='salepromotionapplication',
            constraint=models.CheckConstraint(condition=models.Q(('total_discount_amount__gte', 0)), name='promo_application_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='salepromotionapplication',
            constraint=models.CheckConstraint(condition=models.Q(('removed_at__isnull', True), ('removed_at__gte', models.F('applied_at')), _connector='OR'), name='promo_application_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='salepromotionallocation',
            constraint=models.UniqueConstraint(fields=('application', 'sale_line', 'group_number'), name='promo_allocation_line_group_unique'),
        ),
        migrations.AddConstraint(
            model_name='salepromotionallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_in_group__gt', 0), ('discounted_quantity__gte', 0), ('discounted_quantity__lte', models.F('quantity_in_group'))), name='promo_allocation_quantities_valid'),
        ),
        migrations.AddConstraint(
            model_name='salepromotionallocation',
            constraint=models.CheckConstraint(condition=models.Q(('original_amount__gte', 0), ('final_amount__gte', 0), ('discount_amount__gte', 0), ('final_amount__lte', models.F('original_amount'))), name='promo_allocation_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='salepromotionallocation',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount', django.db.models.expressions.CombinedExpression(models.F('original_amount'), '-', models.F('final_amount')))), name='promo_allocation_difference_valid'),
        ),
    ]
