# Generated by Django 5.2.17 on 2026-09-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionrule',
            name='fixed_discount_scope',
            field=models.CharField(choices=[('PER_ITEM', 'Per ogni articolo scontato'), ('PER_GROUP', 'Una volta per gruppo')], default='PER_ITEM', max_length=16),
        ),
    ]
