# Generated by Django 5.2.17 on 2026-08-30 00:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_productvariant_productbarcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantSalePrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manuale'), ('SUGGESTED', 'Prezzo suggerito'), ('IMPORT', 'Importazione')], default='MANUAL', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_variant_sale_prices', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_prices', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('variant', '-valid_from'),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='pricing_sale_price_amount_positive'), models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='pricing_sale_price_dates_valid'), models.UniqueConstraint(condition=models.Q(('valid_until__isnull', True)), fields=('variant',), name='pricing_one_current_sale_price_per_variant')],
            },
        ),
    ]
