# Generated by Django 5.2.17 on 2026-08-30 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentPurpose',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('notice_text', models.TextField()),
                ('notice_version', models.CharField(max_length=32)),
                ('requires_double_opt_in', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=64)),
                ('country_code', models.CharField(default='IT', max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'customer_code'),
            },
        ),
        migrations.CreateModel(
            name='CustomerChild',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('expected_birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('FEMALE', 'Femminile'), ('MALE', 'Maschile'), ('NOT_SPECIFIED', 'Non specificato')], default='NOT_SPECIFIED', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='children', to='customers.customer')),
            ],
            options={
                'ordering': ('first_name', 'birth_date'),
            },
        ),
        migrations.CreateModel(
            name='CustomerConsentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('GRANTED', 'Concesso'), ('WITHDRAWN', 'Revocato'), ('CONFIRMATION_REQUESTED', 'Conferma richiesta'), ('CONFIRMED', 'Confermato')], max_length=24)),
                ('notice_version', models.CharField(max_length=32)),
                ('notice_text', models.TextField()),
                ('occurred_at', models.DateTimeField()),
                ('channel', models.CharField(choices=[('IN_STORE_SMARTPHONE', 'Smartphone in negozio'), ('WEB', 'Web'), ('EMAIL', 'Email'), ('IMPORT', 'Importazione')], max_length=24)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_customer_consents', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_events', to='customers.customer')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_events', to='customers.consentpurpose')),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='follow_up_events', to='customers.customerconsentevent')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
                'indexes': [models.Index(fields=['customer', 'purpose', 'occurred_at'], name='customer_consent_history_idx')],
            },
        ),
    ]
