# Generated by Django 5.2.17 on 2026-08-30 19:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyEarningRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('spend_block_amount', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('points_per_block', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(('spend_block_amount__gt', 0)), name='loyalty_spend_block_positive'), models.CheckConstraint(condition=models.Q(('points_per_block__gt', 0)), name='loyalty_points_per_block_positive')],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyEarningActivation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('singleton_key', models.BooleanField(default=True, editable=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loyalty_earning_activations', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='loyalty.loyaltyearningrule')),
            ],
            options={
                'ordering': ('-valid_from',),
            },
        ),
        migrations.CreateModel(
            name='LoyaltyPointMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points_delta', models.IntegerField()),
                ('movement_type', models.CharField(choices=[('EARNED', 'Punti guadagnati'), ('RETURN_REVERSAL', 'Storno per reso'), ('REWARD_REDEMPTION', 'Riscatto premio'), ('MANUAL_ADJUSTMENT', 'Rettifica manuale'), ('EXPIRATION', 'Scadenza punti')], max_length=24)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loyalty_point_movements', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loyalty_point_movements', to='customers.customer')),
                ('earning_activation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='point_movements', to='loyalty.loyaltyearningactivation')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='LoyaltyRewardDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('reward_type', models.CharField(choices=[('FIXED_AMOUNT_DISCOUNT', 'Buono sconto a importo fisso'), ('PERCENTAGE_DISCOUNT', 'Sconto percentuale')], max_length=32)),
                ('points_cost', models.PositiveIntegerField()),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('validity_days', models.PositiveSmallIntegerField(default=180)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('points_cost', 'name'),
                'constraints': [models.CheckConstraint(condition=models.Q(('points_cost__gt', 0)), name='loyalty_reward_points_cost_positive'), models.CheckConstraint(condition=models.Q(('minimum_purchase_amount__gte', 0)), name='loyalty_reward_min_purchase_non_negative'), models.CheckConstraint(condition=models.Q(('validity_days__gt', 0)), name='loyalty_reward_validity_days_positive'), models.CheckConstraint(condition=models.Q(models.Q(('fixed_amount__gt', 0), ('percentage__isnull', True), ('reward_type', 'FIXED_AMOUNT_DISCOUNT')), models.Q(('fixed_amount__isnull', True), ('percentage__gt', 0), ('percentage__lte', 100), ('reward_type', 'PERCENTAGE_DISCOUNT')), _connector='OR'), name='loyalty_reward_definition_value_valid')],
            },
        ),
        migrations.CreateModel(
            name='IssuedLoyaltyReward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('reward_type', models.CharField(choices=[('FIXED_AMOUNT_DISCOUNT', 'Buono sconto a importo fisso'), ('PERCENTAGE_DISCOUNT', 'Sconto percentuale')], max_length=32)),
                ('points_spent', models.PositiveIntegerField()),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Attivo'), ('USED', 'Utilizzato'), ('EXPIRED', 'Scaduto'), ('CANCELLED', 'Annullato')], default='ACTIVE', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loyalty_rewards', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_loyalty_rewards', to='customers.customer')),
                ('point_movement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issued_reward', to='loyalty.loyaltypointmovement')),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_rewards', to='loyalty.loyaltyrewarddefinition')),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='loyaltyearningactivation',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gt', models.F('valid_from')), _connector='OR'), name='loyalty_activation_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='loyaltyearningactivation',
            constraint=models.UniqueConstraint(condition=models.Q(('valid_until__isnull', True)), fields=('singleton_key',), name='loyalty_one_open_earning_activation'),
        ),
        migrations.AddIndex(
            model_name='loyaltypointmovement',
            index=models.Index(fields=['customer', 'occurred_at'], name='loyalty_cust_points_date_idx'),
        ),
        migrations.AddIndex(
            model_name='loyaltypointmovement',
            index=models.Index(fields=['source_type', 'source_id'], name='loyalty_points_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='loyaltypointmovement',
            constraint=models.CheckConstraint(condition=models.Q(('points_delta', 0), _negated=True), name='loyalty_points_delta_non_zero'),
        ),
        migrations.AddIndex(
            model_name='issuedloyaltyreward',
            index=models.Index(fields=['customer', 'status', 'expires_at'], name='loyalty_reward_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='issuedloyaltyreward',
            constraint=models.CheckConstraint(condition=models.Q(('points_spent__gt', 0)), name='loyalty_issued_points_positive'),
        ),
        migrations.AddConstraint(
            model_name='issuedloyaltyreward',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('issued_at'))), name='loyalty_issued_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='issuedloyaltyreward',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_purchase_amount__gte', 0)), name='loyalty_issued_min_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='issuedloyaltyreward',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fixed_amount__gt', 0), ('percentage__isnull', True), ('remaining_amount__gte', 0), ('remaining_amount__lte', models.F('fixed_amount')), ('reward_type', 'FIXED_AMOUNT_DISCOUNT')), models.Q(('fixed_amount__isnull', True), ('percentage__gt', 0), ('percentage__lte', 100), ('remaining_amount__isnull', True), ('reward_type', 'PERCENTAGE_DISCOUNT')), _connector='OR'), name='loyalty_issued_value_valid'),
        ),
    ]
