# Generated by Django 5.2.17 on 2026-09-02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loyalty", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sales", "0004_saledraftchange"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoyaltyRewardRedemption",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("discount_amount", models.DecimalField(max_digits=12, decimal_places=2)),
                ("status", models.CharField(max_length=16, choices=[("APPLIED", "Applicato"), ("CANCELLED", "Annullato")], default="APPLIED")),
                ("cancelled_at", models.DateTimeField(null=True, blank=True)),
                ("cancellation_reason", models.CharField(max_length=255, blank=True)),
                ("applied_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="applied_loyalty_reward_redemptions", to=settings.AUTH_USER_MODEL)),
                ("cancelled_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cancelled_loyalty_reward_redemptions", to=settings.AUTH_USER_MODEL, null=True, blank=True)),
                ("reward", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="redemptions", to="loyalty.issuedloyaltyreward")),
                ("sale", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="loyalty_reward_redemptions", to="sales.sale")),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.AddConstraint(model_name="loyaltyrewardredemption", constraint=models.UniqueConstraint(fields=("reward", "sale"), name="loyalty_reward_sale_unique")),
        migrations.AddConstraint(model_name="loyaltyrewardredemption", constraint=models.CheckConstraint(condition=models.Q(("discount_amount__gt", 0)), name="loyalty_reward_redemption_amount_positive")),
        migrations.AddConstraint(model_name="loyaltyrewardredemption", constraint=models.CheckConstraint(condition=(models.Q(status="APPLIED", cancelled_at__isnull=True, cancelled_by__isnull=True, cancellation_reason="") | models.Q(status="CANCELLED", cancelled_at__isnull=False, cancelled_by__isnull=False, cancellation_reason__gt="")), name="loyalty_reward_redemption_audit")),
    ]
