# Generated by Django 5.2.17 on 2026-08-30 00:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_productvariant_productbarcode_and_more'),
        ('core', '0002_seed_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='core.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('location', 'variant'),
                'constraints': [models.UniqueConstraint(fields=('variant', 'location'), name='inventory_variant_location_unique')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('INITIAL_STOCK', 'Carico iniziale'), ('PURCHASE_RECEIPT', 'Ricezione fornitore'), ('SALE', 'Vendita'), ('CUSTOMER_RETURN', 'Reso cliente'), ('SUPPLIER_RETURN', 'Reso fornitore'), ('TRANSFER_IN', 'Trasferimento in entrata'), ('TRANSFER_OUT', 'Trasferimento in uscita'), ('ADJUSTMENT_IN', 'Rettifica in entrata'), ('ADJUSTMENT_OUT', 'Rettifica in uscita'), ('INVENTORY_GAIN', 'Eccedenza inventario'), ('INVENTORY_LOSS', 'Ammanco inventario')], max_length=24)),
                ('quantity_delta', models.IntegerField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=120)),
                ('transfer_group_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='core.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-occurred_at', '-created_at'),
                'indexes': [models.Index(fields=['variant', 'occurred_at'], name='inv_move_variant_date_idx'), models.Index(fields=['location', 'occurred_at'], name='inv_move_location_date_idx'), models.Index(fields=['source_type', 'source_id'], name='inventory_move_source_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='inventory_movement_quantity_non_zero'), models.CheckConstraint(condition=models.Q(('unit_cost__isnull', True), ('unit_cost__gte', 0), _connector='OR'), name='inventory_movement_unit_cost_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ('INITIAL_STOCK', 'PURCHASE_RECEIPT', 'CUSTOMER_RETURN', 'TRANSFER_IN', 'ADJUSTMENT_IN', 'INVENTORY_GAIN')), ('quantity_delta__gt', 0)), models.Q(('movement_type__in', ('SALE', 'SUPPLIER_RETURN', 'TRANSFER_OUT', 'ADJUSTMENT_OUT', 'INVENTORY_LOSS')), ('quantity_delta__lt', 0)), _connector='OR'), name='inventory_movement_type_quantity_sign_valid')],
            },
        ),
        migrations.CreateModel(
            name='VariantInventoryCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weighted_average_unit_cost', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('inventory_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('last_movement_at', models.DateTimeField(blank=True, null=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_cost', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('variant',),
                'constraints': [models.CheckConstraint(condition=models.Q(('weighted_average_unit_cost__gte', 0)), name='inventory_weighted_cost_non_negative'), models.CheckConstraint(condition=models.Q(('inventory_value__gte', 0)), name='inventory_value_non_negative')],
            },
        ),
    ]
