# Generated by Django 5.2.17 on 2026-09-01 22:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_productvariant_productbarcode_and_more'),
        ('core', '0003_shopsettings_voucher_validity_months'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('scope', models.CharField(choices=[('FULL', 'Inventario completo'), ('PARTIAL', 'Inventario parziale')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('IN_PROGRESS', 'In corso'), ('CONFIRMED', 'Confermato'), ('CANCELLED', 'Annullato')], default='DRAFT', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('brands', models.ManyToManyField(blank=True, related_name='inventory_count_sessions', to='catalog.brand')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_inventory_count_sessions', to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, related_name='inventory_count_sessions', to='catalog.category')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_inventory_count_sessions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_count_sessions', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_count_sessions', to='core.location')),
                ('products', models.ManyToManyField(blank=True, related_name='inventory_count_sessions', to='catalog.product')),
                ('seasons', models.ManyToManyField(blank=True, related_name='inventory_count_sessions', to='catalog.season')),
                ('variants', models.ManyToManyField(blank=True, related_name='inventory_count_sessions', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.PositiveIntegerField()),
                ('counted_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('difference_quantity', models.IntegerField(blank=True, null=True)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('expected_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('counted_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('difference_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('adjustment_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_count_line', to='inventory.stockmovement')),
                ('counted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counted_inventory_lines', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_count_lines', to='catalog.productvariant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorycountsession')),
            ],
            options={
                'ordering': ('variant',),
            },
        ),
        migrations.AddIndex(
            model_name='inventorycountsession',
            index=models.Index(fields=['location', 'status', 'created_at'], name='inv_count_loc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycountsession',
            index=models.Index(fields=['confirmed_at'], name='inv_count_confirmed_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('confirmed_at__isnull', False), ('confirmed_by__isnull', False), ('status', 'CONFIRMED')), models.Q(('status', 'CONFIRMED'), _negated=True), _connector='OR'), name='inv_count_confirmed_audit'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountsession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'CANCELLED')), models.Q(('status', 'CANCELLED'), _negated=True), _connector='OR'), name='inv_count_cancelled_audit'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountline',
            constraint=models.UniqueConstraint(fields=('session', 'variant'), name='inv_count_session_variant_unique'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost_snapshot__gte', 0)), name='inv_count_unit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountline',
            constraint=models.CheckConstraint(condition=models.Q(('expected_value__gte', 0)), name='inv_count_expected_value_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('counted_at__isnull', True), ('counted_by__isnull', True), ('counted_quantity__isnull', True), ('counted_value__isnull', True), ('difference_quantity__isnull', True), ('difference_value__isnull', True)), models.Q(('counted_at__isnull', False), ('counted_by__isnull', False), ('counted_quantity__isnull', False), ('counted_value__isnull', False), ('difference_quantity__isnull', False), ('difference_value__isnull', False)), _connector='OR'), name='inv_count_line_count_audit'),
        ),
    ]
