# Generated by Django 5.2.17 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorycountsession_inventorycountline_and_more"),
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycountsession",
            name="suppliers",
            field=models.ManyToManyField(
                blank=True,
                related_name="inventory_count_sessions",
                to="suppliers.supplier",
            ),
        ),
    ]
