# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_inventorycountsession_suppliers"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stockbalance",
            index=models.Index(
                fields=("location", "quantity_on_hand"),
                name="inventory_stock_loc_qty_idx",
            ),
        ),
    ]
