# Generated by Django 5.2.17 on 2026-08-31 20:12

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_productvariant_productbarcode_and_more'),
        ('core', '0002_seed_initial_data'),
        ('customers', '0001_initial'),
        ('pricing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_registers', to='core.location')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aperta'), ('CLOSED', 'Chiusa')], default='OPEN', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opening_cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('expected_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('counted_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_difference', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='sales.cashregister')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_cash_sessions', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_cash_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=32)),
                ('channel', models.CharField(choices=[('POS', 'Negozio'), ('SHOPIFY', 'Shopify')], default='POS', max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Aperta'), ('CONFIRMED', 'Confermata'), ('CANCELLED', 'Annullata')], default='OPEN', max_length=16)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('calculated_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('manual_total_override_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manual_total_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_cost_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('manual_override_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_sales', to=settings.AUTH_USER_MODEL)),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='sales.cashsession')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.location')),
                ('manual_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manually_overridden_sales', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-opened_at',),
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('sku_snapshot', models.CharField(max_length=64)),
                ('product_name_snapshot', models.CharField(max_length=160)),
                ('color_snapshot', models.CharField(blank=True, max_length=120)),
                ('size_snapshot', models.CharField(blank=True, max_length=32)),
                ('pricing_mode', models.CharField(choices=[('STANDARD', 'Prezzo normale'), ('SALE', 'Saldo'), ('PROMOTION', 'Promozione')], default='STANDARD', max_length=16)),
                ('base_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manual_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost_snapshot', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('total_cost_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('manual_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('manual_override_reason', models.CharField(blank=True, max_length=255)),
                ('manual_override_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manually_overridden_sale_lines', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale')),
                ('source_sale_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='pricing.variantsaleprice')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH', 'Contanti'), ('CARD', 'Carta'), ('GIFT_CARD', 'Gift card'), ('STORE_CREDIT', 'Buono reso'), ('OTHER', 'Altro')], max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cash_received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cash_change_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=120)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_sale_payments', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'ordering': ('occurred_at', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN')), fields=('cash_register',), name='sales_one_open_session_per_register'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('opening_cash_amount__gte', 0)), name='sales_opening_cash_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('expected_cash_amount__isnull', True), ('expected_cash_amount__gte', 0), _connector='OR'), name='sales_expected_cash_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('counted_cash_amount__isnull', True), ('counted_cash_amount__gte', 0), _connector='OR'), name='sales_counted_cash_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='cashsession',
            constraint=models.CheckConstraint(condition=models.Q(('closed_at__isnull', True), ('closed_at__gte', models.F('opened_at')), _connector='OR'), name='sales_cash_session_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('number',), name='sales_number_unique_when_present'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0), ('discount_amount__gte', 0), ('tax_amount__gte', 0), ('calculated_total_amount__gte', 0), ('final_total_amount__gte', 0), ('total_cost_amount__gte', 0)), name='sales_totals_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('manual_total_override_amount__isnull', True), ('manual_total_override_amount__gte', 0), _connector='OR'), name='sales_manual_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CONFIRMED'), _negated=True), models.Q(('number', ''), _negated=True), _connector='OR'), name='sales_confirmed_number_required'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.UniqueConstraint(fields=('sale', 'variant'), name='sales_sale_variant_unique'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('base_unit_price__gte', 0), ('final_unit_price__gte', 0), ('gross_amount__gte', 0), ('discount_amount__gte', 0), ('net_amount__gte', 0), ('tax_amount__gte', 0), ('unit_cost_snapshot__gte', 0), ('total_cost_amount__gte', 0)), name='sales_line_amounts_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('manual_unit_price__isnull', True), ('manual_unit_price__gte', 0), _connector='OR'), name='sales_line_manual_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('tax_percentage__gte', 0), ('tax_percentage__lte', 100)), name='sales_line_tax_percentage_valid'),
        ),
        migrations.AddConstraint(
            model_name='salepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sales_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='salepayment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cash_change_amount', django.db.models.expressions.CombinedExpression(models.F('cash_received_amount'), '-', models.F('amount'))), ('cash_received_amount__gte', models.F('amount')), ('method', 'CASH')), models.Q(models.Q(('method', 'CASH'), _negated=True), ('cash_change_amount__isnull', True), ('cash_received_amount__isnull', True)), _connector='OR'), name='sales_payment_cash_fields_valid'),
        ),
    ]
