# Generated by Django 5.2.17 on 2026-09-02 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salenumbersequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleDraftChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('REMOVE_LINE', 'Rimozione riga'), ('REMOVE_PAYMENT', 'Rimozione pagamento'), ('CANCEL', 'Annullamento')], max_length=32)),
                ('reason', models.CharField(max_length=255)),
                ('snapshot', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_changes', to='sales.sale')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
            },
        ),
    ]
