# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_saledraftchange"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=("status", "confirmed_at"),
                name="sales_status_confirmed_idx",
            ),
        ),
    ]
