# Generated by Django 5.2.17 on 2026-09-01 21:54

import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_shopsettings_voucher_validity_months'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=120)),
                ('document_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('OPEN', 'Da pagare'), ('PARTIALLY_PAID', 'Parzialmente pagata'), ('PAID', 'Pagata'), ('CANCELLED', 'Annullata')], default='DRAFT', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_expenses', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.location')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='suppliers.supplier')),
            ],
            options={
                'ordering': ('-document_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='ExpenseAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='expenses/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='expenses.expense')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_expense_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='expenses.expensecategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.expensecategory'),
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('CASH', 'Contanti'), ('CARD', 'Carta'), ('BANK_TRANSFER', 'Bonifico'), ('DIRECT_DEBIT', 'Addebito diretto'), ('OTHER', 'Altro')], max_length=24)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='expenses.expense')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_expense_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('paid_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ExpenseStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(choices=[('DRAFT', 'Bozza'), ('OPEN', 'Da pagare'), ('PARTIALLY_PAID', 'Parzialmente pagata'), ('PAID', 'Pagata'), ('CANCELLED', 'Annullata')], max_length=24)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Bozza'), ('OPEN', 'Da pagare'), ('PARTIALLY_PAID', 'Parzialmente pagata'), ('PAID', 'Pagata'), ('CANCELLED', 'Annullata')], max_length=24)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changed_expense_statuses', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='expenses.expense')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'due_date'], name='expense_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'document_date'], name='expense_category_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amount__gte', 0), ('tax_amount__gte', 0), ('total_amount__gt', 0), ('paid_amount__gte', 0), ('paid_amount__lte', models.F('total_amount'))), name='expense_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('taxable_amount'), '+', models.F('tax_amount')))), name='expense_total_matches'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('due_date__isnull', True), ('due_date__gte', models.F('document_date')), _connector='OR'), name='expense_due_date_valid'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PAID'), _negated=True), ('paid_amount', models.F('total_amount')), _connector='OR'), name='expense_paid_balance_valid'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'PARTIALLY_PAID'), _negated=True), ('paid_amount__gt', 0), _connector='OR'), name='expense_partial_balance_pos'),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_payment_amount_pos'),
        ),
        migrations.AddConstraint(
            model_name='expensestatuschange',
            constraint=models.CheckConstraint(condition=models.Q(('previous_status', models.F('new_status')), _negated=True), name='expense_status_change_valid'),
        ),
    ]
