# Generated by Django 5.2.17 on 2026-09-01 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_productvariant_productbarcode_and_more'),
        ('core', '0003_shopsettings_voucher_validity_months'),
        ('notifications', '0001_initial'),
        ('purchasing', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Da riordinare'), ('ORDERED', 'Ordinato'), ('COMPLETED', 'Completato'), ('REMOVED', 'Rimosso')], default='PENDING', max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('ordered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.CharField(blank=True, max_length=255)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_reorder_items', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_reorder_items', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_items', to='core.location')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordered_reorder_items', to=settings.AUTH_USER_MODEL)),
                ('purchase_order_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reorder_items', to='purchasing.purchaseorderline')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='removed_reorder_items', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reorder_items', to='suppliers.supplier')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('supplier', 'variant', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReorderItemChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_quantity', models.PositiveIntegerField()),
                ('new_quantity', models.PositiveIntegerField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_item_changes', to=settings.AUTH_USER_MODEL)),
                ('new_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='new_reorder_changes', to='suppliers.supplier')),
                ('previous_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='previous_reorder_changes', to='suppliers.supplier')),
                ('reorder_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='reorders.reorderitem')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReorderNotificationLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reorder_link', to='notifications.notification')),
                ('reorder_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notification_links', to='reorders.reorderitem')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='reorderitem',
            index=models.Index(fields=['status', 'supplier'], name='reorder_status_supplier_idx'),
        ),
        migrations.AddConstraint(
            model_name='reorderitem',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('variant', 'location'), name='reorder_pending_variant_loc'),
        ),
        migrations.AddConstraint(
            model_name='reorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='reorder_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='reorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ORDERED'), _negated=True), models.Q(('ordered_at__isnull', False), ('ordered_by__isnull', False), ('purchase_order_line__isnull', False)), _connector='OR'), name='reorder_ordered_audit'),
        ),
        migrations.AddConstraint(
            model_name='reorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REMOVED'), _negated=True), models.Q(('removed_at__isnull', False), ('removed_by__isnull', False)), _connector='OR'), name='reorder_removed_audit'),
        ),
        migrations.AddConstraint(
            model_name='reorderitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'COMPLETED'), _negated=True), models.Q(('completed_at__isnull', False), ('completed_by__isnull', False)), _connector='OR'), name='reorder_completed_audit'),
        ),
    ]
