# Generated by Django 5.2.17 on 2026-09-01 22:02

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('direction', models.CharField(choices=[('INCOMING', 'Ricevuto'), ('OUTGOING', 'Emesso'), ('INTERNAL', 'Interno')], max_length=16)),
                ('requires_number', models.BooleanField(default=True)),
                ('automatic_numbering', models.BooleanField(default=False)),
                ('number_prefix', models.CharField(blank=True, max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('INCOMING', 'Ricevuto'), ('OUTGOING', 'Emesso'), ('INTERNAL', 'Interno')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Bozza'), ('REGISTERED', 'Registrato'), ('ISSUED', 'Emesso'), ('CANCELLED', 'Annullato')], default='DRAFT', max_length=16)),
                ('number', models.CharField(blank=True, max_length=80)),
                ('document_date', models.DateField()),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('counterparty_name', models.CharField(blank=True, max_length=200)),
                ('counterparty_vat_number', models.CharField(blank=True, max_length=32)),
                ('counterparty_tax_code', models.CharField(blank=True, max_length=32)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_business_documents', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_business_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='documents.documenttype')),
            ],
            options={
                'ordering': ('-document_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='documents.businessdocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_document_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(choices=[('DRAFT', 'Bozza'), ('REGISTERED', 'Registrato'), ('ISSUED', 'Emesso'), ('CANCELLED', 'Annullato')], max_length=16)),
                ('new_status', models.CharField(choices=[('DRAFT', 'Bozza'), ('REGISTERED', 'Registrato'), ('ISSUED', 'Emesso'), ('CANCELLED', 'Annullato')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changed_document_statuses', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status_changes', to='documents.businessdocument')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('previous_status', models.F('new_status')), _negated=True), name='document_status_change_valid')],
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='number_sequences', to='documents.documenttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document_type', 'year'), name='document_sequence_type_year')],
            },
        ),
        migrations.AddIndex(
            model_name='businessdocument',
            index=models.Index(fields=['status', 'document_date'], name='document_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='businessdocument',
            index=models.Index(fields=['source_type', 'source_id'], name='document_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='businessdocument',
            constraint=models.UniqueConstraint(condition=models.Q(('number', ''), _negated=True), fields=('document_type', 'number'), name='document_type_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='businessdocument',
            constraint=models.CheckConstraint(condition=models.Q(('taxable_amount__gte', 0), ('tax_amount__gte', 0), ('total_amount__gte', 0)), name='document_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='businessdocument',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount', django.db.models.expressions.CombinedExpression(models.F('taxable_amount'), '+', models.F('tax_amount')))), name='document_total_matches'),
        ),
        migrations.AddConstraint(
            model_name='businessdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_id__isnull', True), ('source_type', '')), models.Q(models.Q(('source_type', ''), _negated=True), ('source_id__isnull', False)), _connector='OR'), name='document_source_pair_valid'),
        ),
        migrations.AddConstraint(
            model_name='businessdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ISSUED'), _negated=True), ('issued_at__isnull', False), _connector='OR'), name='document_issued_audit'),
        ),
        migrations.AddConstraint(
            model_name='businessdocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'REGISTERED'), _negated=True), ('registered_at__isnull', False), _connector='OR'), name='document_registered_audit'),
        ),
    ]
