import { useEffect, useState } from "react";
import { BanknoteArrowDown, CircleDollarSign, Plus, Search } from "lucide-react";
import { request } from "../api";
import "../products.css";

const list = (data) => data?.results || data || [];
const today = () => new Date().toISOString().slice(0, 10);
const emptyForm = { category: "", supplier: "", description: "", document_number: "", document_date: today(), due_date: "", taxable_amount: "", tax_amount: "0.00", total_amount: "", notes: "" };
const euro = new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR" });
const statusLabel = { DRAFT: "Bozza", OPEN: "Da pagare", PARTIALLY_PAID: "Parzialmente pagata", PAID: "Pagata", CANCELLED: "Annullata" };

export default function CostsPage() {
  const [expenses, setExpenses] = useState([]); const [categories, setCategories] = useState([]); const [suppliers, setSuppliers] = useState([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("OPEN");
  const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false);
  const load = async (search = query, selectedStatus = status) => { try { const params = new URLSearchParams(); if (search.trim()) params.set("search", search.trim()); if (selectedStatus !== "ALL") params.set("status", selectedStatus); const [expenseData, categoryData, supplierData] = await Promise.all([request(`/expenses/expenses/?${params}`), request("/expenses/categories/?is_active=true"), request("/suppliers/suppliers/?is_active=true")]); setExpenses(list(expenseData)); setCategories(list(categoryData)); setSuppliers(list(supplierData)); } catch (error) { setSuccess(false); setMessage(error.message); } };
  useEffect(() => { load("", "OPEN"); }, []);
  useEffect(() => { if (!message) return undefined; const timer = setTimeout(() => setMessage(""), 4000); return () => clearTimeout(timer); }, [message]);
  const update = (field, value) => setForm((current) => { const next = { ...current, [field]: value }; if (field === "taxable_amount" || field === "tax_amount") next.total_amount = (Number(field === "taxable_amount" ? value : current.taxable_amount || 0) + Number(field === "tax_amount" ? value : current.tax_amount || 0)).toFixed(2); return next; });
  const openCreate = () => { setForm(emptyForm); setMessage(""); setFormOpen(true); };
  async function createExpense(event) { event.preventDefault(); setSaving(true); setMessage(""); try { await request("/expenses/expenses/", { method: "POST", body: JSON.stringify({ ...form, supplier: form.supplier || null, due_date: form.due_date || null, taxable_amount: form.taxable_amount, tax_amount: form.tax_amount || "0.00", total_amount: form.total_amount }) }); setFormOpen(false); setSuccess(true); setMessage("Costo registrato come bozza."); setStatus("DRAFT"); await load("", "DRAFT"); } catch (error) { setSuccess(false); setMessage(error.message); } finally { setSaving(false); } }
  async function openExpense(expense) { try { await request(`/expenses/expenses/${expense.id}/open/`, { method: "POST", body: JSON.stringify({}) }); setSuccess(true); setMessage("Costo aperto e pronto per il pagamento."); await load(); } catch (error) { setSuccess(false); setMessage(error.message); } }
  const supplierName = (id) => suppliers.find((supplier) => supplier.id === id)?.business_name || "Spesa interna";
  const date = (value) => value ? new Intl.DateTimeFormat("it-IT").format(new Date(`${value}T00:00:00`)) : "Non indicata";
  return <section className="products-page costs-page">
    <style>{`.cost-form{display:grid;grid-template-columns:1.25fr repeat(3,minmax(130px,1fr));gap:14px;align-items:end;padding:20px;border-radius:14px;background:#fff;box-shadow:0 7px 22px #25171a09}.cost-form label{display:grid;gap:6px;font-size:11px;font-weight:900}.cost-form input,.cost-form select{box-sizing:border-box;width:100%;height:42px;border:1px solid #ded9db;border-radius:8px;padding:0 10px;background:#fff;font:inherit}.cost-copy{grid-row:span 2}.cost-form .cost-notes{grid-column:2/4}.cost-form .cost-total input{background:#f7f5f4;font-weight:900}.cost-heading,.cost-row{display:grid;grid-template-columns:minmax(180px,1.2fr) minmax(150px,.8fr) 130px 130px 120px 100px;align-items:center;gap:18px;padding:15px 22px}.cost-heading{color:#8b858a;font-size:10px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}.cost-row{border-top:1px solid #eeeaea}.cost-row>div{display:grid;gap:4px}.cost-row strong{font-size:13px}.cost-row span{color:#817b80;font-size:12px}.cost-row>b{color:#b70018;font-size:13px}.cost-status{justify-self:start;padding:5px 8px;border-radius:7px;background:#fff3d9;color:#a56800;font-size:10px;font-style:normal;font-weight:900}.cost-status.open{background:#edf3ff;color:#3762aa}.cost-status.paid{background:#edf9f1;color:#167444}.cost-status.partially_paid{background:#fff3d9;color:#a56800}.cost-status.cancelled{background:#fff0f2;color:#b00019}.cost-open{justify-self:start;height:33px;border:0;border-radius:7px;padding:0 11px;background:#ed001b;color:#fff;font-size:11px;font-weight:900;cursor:pointer}@media(max-width:900px){.cost-form{grid-template-columns:1fr 1fr}.cost-copy{grid-column:1/-1;grid-row:auto}.cost-form .cost-notes{grid-column:auto}.cost-heading{display:none}.cost-row{grid-template-columns:1fr auto;padding:16px}.cost-row>span{display:none}.cost-status{grid-column:2;grid-row:1}.cost-open{grid-column:1;grid-row:2}}@media(max-width:560px){.cost-form{grid-template-columns:1fr}.cost-form .inline-form-actions button{flex:1}}`}</style>
    <div className="page-title-row"><div><p className="eyebrow">Acquisti</p><h2>Costi</h2><span>Spese operative, fatture e pagamenti da gestire per il negozio.</span></div><button className="primary-action" onClick={openCreate}><Plus size={17} /> Nuovo costo</button></div>
    {formOpen && <form className="cost-form" onSubmit={createExpense}><div className="inventory-form-copy cost-copy"><p className="eyebrow">Nuovo costo</p><h3>Registra una spesa</h3><span>Salvala in bozza, poi aprila quando è pronta per essere pagata.</span></div><label>Categoria<select required value={form.category} onChange={(event) => update("category", event.target.value)}><option value="">Seleziona categoria</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Fornitore<select value={form.supplier} onChange={(event) => update("supplier", event.target.value)}><option value="">Spesa senza fornitore</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.business_name}</option>)}</select></label><label>Descrizione<input required value={form.description} onChange={(event) => update("description", event.target.value)} placeholder="Es. Utenza elettrica" /></label><label>Numero documento<input value={form.document_number} onChange={(event) => update("document_number", event.target.value)} /></label><label>Data documento<input required type="date" value={form.document_date} onChange={(event) => update("document_date", event.target.value)} /></label><label>Scadenza pagamento<input type="date" value={form.due_date} onChange={(event) => update("due_date", event.target.value)} /></label><label>Imponibile €<input required min="0" step="0.01" type="number" value={form.taxable_amount} onChange={(event) => update("taxable_amount", event.target.value)} /></label><label>IVA €<input required min="0" step="0.01" type="number" value={form.tax_amount} onChange={(event) => update("tax_amount", event.target.value)} /></label><label className="cost-total">Totale €<input required readOnly value={form.total_amount} /></label><label className="cost-notes">Note<input value={form.notes} onChange={(event) => update("notes", event.target.value)} placeholder="Facoltative" /></label><div className="inline-form-actions"><button type="button" className="secondary-action" onClick={() => setFormOpen(false)}>Annulla</button><button className="primary-action" disabled={saving}>{saving ? "Salvataggio..." : "Crea bozza"}</button></div></form>}
    {message && <p className={success ? "operation-success" : "catalog-error"}>{message}</p>}
    <div className="voucher-filters"><form className="products-search" onSubmit={(event) => { event.preventDefault(); load(); }}><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cerca descrizione o numero documento" /><button>Ricerca</button></form><div className="status-tabs">{[["DRAFT", "Bozze"], ["OPEN", "Da pagare"], ["PARTIALLY_PAID", "Parziali"], ["PAID", "Pagati"], ["ALL", "Tutti"]].map(([value, label]) => <button type="button" className={status === value ? "active" : ""} key={value} onClick={() => { setStatus(value); load(query, value); }}>{label}</button>)}</div></div>
    <article className="products-list"><div className="cost-heading"><span>Descrizione</span><span>Fornitore</span><span>Documento</span><span>Scadenza</span><span>Totale</span><span>Stato</span></div>{!expenses.length ? <div className="empty-product-state"><BanknoteArrowDown size={28} /><strong>Nessun costo trovato</strong><span>Registra una spesa per tenere sotto controllo uscite e pagamenti.</span></div> : expenses.map((expense) => <div className="cost-row" key={expense.id}><div><strong>{expense.description}</strong><span>{expense.document_date ? date(expense.document_date) : ""}</span></div><span>{supplierName(expense.supplier)}</span><span>{expense.document_number || "Non indicato"}</span><span>{date(expense.due_date)}</span><b>{euro.format(Number(expense.total_amount))}</b>{expense.status === "DRAFT" ? <button className="cost-open" onClick={() => openExpense(expense)}><CircleDollarSign size={14} /> Apri</button> : <em className={`cost-status ${expense.status.toLowerCase()}`}>{statusLabel[expense.status] || expense.status}</em>}</div>)}</article>
  </section>;
}
