import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Eye, FileText, FileUp, Plus, ScanText, Search, X } from "lucide-react";
import { request } from "../api";
import "../products.css";
import "./DocumentsOcrPage.css";

const list = (data) => data?.results || data || [];
const today = () => new Date().toISOString().slice(0, 10);
const blank = () => ({ document_type: "", title: "", number: "", document_date: today(), counterparty_name: "", file: null });
const statusLabel = { DRAFT: "Bozza", REGISTERED: "Registrato", ISSUED: "Emesso", CANCELLED: "Annullato" };
const directionLabel = { INCOMING: "Ricevuto", OUTGOING: "Emesso", INTERNAL: "Interno" };
const date = (value) => value ? new Intl.DateTimeFormat("it-IT").format(new Date(`${value}T00:00:00`)) : "Non indicata";
const amount = (value) => Number.parseFloat(String(value).replace(",", ".")) || 0;
const money = (value) => amount(value).toFixed(2);
const lineTotal = (item) => amount(item.quantity) * amount(item.unit_price);

function latest(items, attachment) {
  return items.filter((item) => item.attachment === attachment).sort((a, b) => new Date(b.created_at) - new Date(a.created_at))[0];
}

function makeReview(analysis) {
  const proposal = analysis.proposed_data || {};
  const saved = proposal.review || {};
  return {
    supplier_name: saved.supplier_name ?? proposal.supplier_name ?? "",
    invoice_number: saved.invoice_number ?? proposal.invoice_number ?? "",
    invoice_date: saved.invoice_date ?? proposal.invoice_date ?? "",
    taxable_amount: saved.taxable_amount ?? proposal.taxable_amount ?? "",
    tax_amount: saved.tax_amount ?? proposal.tax_amount ?? "",
    total_amount: saved.total_amount ?? proposal.total_amount ?? "",
    items: (proposal.items || []).map((item, index) => ({
      accepted: saved.items?.[index]?.accepted ?? true,
      variant_id: saved.items?.[index]?.variant_id ?? "",
      description: saved.items?.[index]?.description ?? item.description ?? "",
      quantity: saved.items?.[index]?.quantity ?? item.quantity ?? "",
      unit_price: saved.items?.[index]?.unit_price ?? item.unit_price ?? "",
      amount: saved.items?.[index]?.amount ?? item.amount ?? "",
    })),
  };
}

export default function DocumentsOcrPage() {
  const [documents, setDocuments] = useState([]); const [types, setTypes] = useState([]); const [attachments, setAttachments] = useState([]); const [analyses, setAnalyses] = useState([]); const [variants, setVariants] = useState([]);
  const [query, setQuery] = useState(""); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState(blank()); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false);
  const [reviewAnalysis, setReviewAnalysis] = useState(null); const [review, setReview] = useState(null); const [reviewSaving, setReviewSaving] = useState(false);
  const notice = (text, ok = true) => { setSuccess(ok); setMessage(text); };
  const load = async () => { try { const [a, b, c, d, e] = await Promise.all([request("/documents/documents/"), request("/documents/types/?is_active=True"), request("/documents/attachments/"), request("/documents/ocr-analyses/"), request("/catalog/variants/?page_size=200")]); setDocuments(list(a)); setTypes(list(b)); setAttachments(list(c)); setAnalyses(list(d)); setVariants(list(e)); } catch (error) { notice(error.message, false); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!message) return undefined; const timer = setTimeout(() => setMessage(""), 4000); return () => clearTimeout(timer); }, [message]);
  const visible = useMemo(() => documents.filter((document) => `${document.title} ${document.number} ${document.counterparty_name}`.toLowerCase().includes(query.toLowerCase())), [documents, query]);
  const typeFor = (id) => types.find((item) => item.id === id); const attachmentFor = (id) => attachments.find((item) => item.document === id);
  const closeReview = () => { setReviewAnalysis(null); setReview(null); };
  const updateReview = (key, value) => setReview((current) => ({ ...current, [key]: value }));
  const updateItem = (index, key, value) => setReview((current) => ({ ...current, items: current.items.map((item, itemIndex) => itemIndex === index ? { ...item, [key]: value } : item) }));
  const reviewSubtotal = review?.items.filter((item) => item.accepted).reduce((total, item) => total + lineTotal(item), 0) || 0;
  const reviewTotal = reviewSubtotal + amount(review?.tax_amount);

  async function upload(event) { event.preventDefault(); if (!form.file) return notice("Seleziona un PDF da allegare.", false); setSaving(true); try { const type = typeFor(form.document_type); const document = await request("/documents/documents/", { method: "POST", body: JSON.stringify({ document_type: form.document_type, direction: type.direction, status: "DRAFT", number: form.number, document_date: form.document_date, title: form.title, taxable_amount: "0.00", tax_amount: "0.00", total_amount: "0.00", counterparty_name: form.counterparty_name }) }); const data = new FormData(); data.append("file", form.file); data.append("description", "Documento caricato per analisi OCR"); await request(`/documents/documents/${document.id}/upload-attachment/`, { method: "POST", body: data }); setFormOpen(false); setForm(blank()); notice("Documento e PDF caricati. Avvia l'OCR per preparare la proposta."); await load(); } catch (error) { notice(error.message, false); } finally { setSaving(false); } }
  async function analyze(attachment) { try { await request(`/documents/attachments/${attachment.id}/analyze-invoice/`, { method: "POST", body: JSON.stringify({}) }); notice("Analisi OCR completata. Apri la proposta per controllare gli articoli."); await load(); } catch (error) { notice(error.message, false); await load(); } }
  async function finalize(document) { try { await request(`/documents/documents/${document.id}/finalize/`, { method: "POST", body: JSON.stringify({ number: document.number }) }); notice("Documento registrato correttamente."); await load(); } catch (error) { notice(error.message, false); } }
  async function saveReview() { setReviewSaving(true); try { const normalizedReview = { ...review, taxable_amount: money(reviewSubtotal), total_amount: money(reviewTotal), items: review.items.map((item) => ({ ...item, amount: money(lineTotal(item)) })) }; await request(`/documents/ocr-analyses/${reviewAnalysis.id}/`, { method: "PATCH", body: JSON.stringify({ proposed_data: { ...reviewAnalysis.proposed_data, review: { ...normalizedReview, status: "CONFIRMED", confirmed_at: new Date().toISOString() } } }) }); closeReview(); notice("Proposta confermata e salvata. Il magazzino non e' stato modificato."); await load(); } catch (error) { notice(error.message, false); } finally { setReviewSaving(false); } }

  return <section className="products-page documents-page">
    <div className="page-title-row"><div><p className="eyebrow">Gestione</p><h2>Documenti e OCR</h2><span>Carica fatture e documenti PDF, poi verifica gli articoli rilevati.</span></div><button className="primary-action" onClick={() => { setForm(blank()); setFormOpen(true); }}><Plus size={17} /> Carica documento</button></div>
    {formOpen && <form className="document-form" onSubmit={upload}><div className="inventory-form-copy document-copy"><p className="eyebrow">Nuovo documento</p><h3>Carica un PDF</h3><span>L'OCR riconosce i dati della fattura dopo il caricamento.</span></div><label>Tipo documento<select required value={form.document_type} onChange={(event) => setForm({ ...form, document_type: event.target.value })}><option value="">Seleziona tipo</option>{types.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Titolo<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label>Numero documento<input value={form.number} onChange={(event) => setForm({ ...form, number: event.target.value })} /></label><label>Data documento<input required type="date" value={form.document_date} onChange={(event) => setForm({ ...form, document_date: event.target.value })} /></label><label>Fornitore<input value={form.counterparty_name} onChange={(event) => setForm({ ...form, counterparty_name: event.target.value })} /></label><label>File PDF<span className="document-file-control"><input id="document-pdf" required type="file" accept="application/pdf" onChange={(event) => setForm({ ...form, file: event.target.files?.[0] || null })} /><button type="button" onClick={() => document.getElementById("document-pdf")?.click()}>Scegli file</button><span>{form.file?.name || "Nessun file selezionato"}</span></span></label><div className="inline-form-actions"><button type="button" className="secondary-action" onClick={() => setFormOpen(false)}>Annulla</button><button className="primary-action" disabled={saving}>{saving ? "Caricamento..." : "Carica"}</button></div></form>}
    {message && <p className={success ? "operation-success" : "catalog-error"}>{message}</p>}
    <div className="voucher-filters"><div className="products-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cerca documento, numero o fornitore" /></div></div>
    <article className="products-list"><div className="document-heading"><span>Documento</span><span>Tipo</span><span>Data</span><span>PDF e OCR</span><span>Stato</span><span>Azioni</span></div>{!visible.length ? <div className="empty-product-state"><FileText size={28} /><strong>Nessun documento trovato</strong><span>Carica un PDF per costruire l'archivio documentale.</span></div> : visible.map((document) => { const attachment = attachmentFor(document.id); const analysis = attachment && latest(analyses, attachment.id); const reviewed = analysis?.proposed_data?.review?.status === "CONFIRMED"; return <div className="document-row" key={document.id}><div><strong>{document.title}</strong><span>{document.number || "Numero non indicato"}{document.counterparty_name ? ` · ${document.counterparty_name}` : ""}</span></div><span>{typeFor(document.document_type)?.name || directionLabel[document.direction]}</span><span>{date(document.document_date)}</span><span>{analysis?.status === "SUCCEEDED" ? reviewed ? "Proposta confermata" : "OCR completato" : analysis?.status === "FAILED" ? "OCR non disponibile" : attachment ? "PDF pronto" : "Nessun PDF"}</span><em className={`document-status ${document.status.toLowerCase()}`}>{statusLabel[document.status] || document.status}</em><div className="document-actions">{analysis?.status === "SUCCEEDED" && <button title="Apri proposta OCR" onClick={() => { setReviewAnalysis(analysis); setReview(makeReview(analysis)); }}><Eye size={16} /></button>}{attachment && <button title="Analizza fattura con OCR" onClick={() => analyze(attachment)}><ScanText size={16} /></button>}{document.status === "DRAFT" && reviewed && <button title="Registra documento" onClick={() => finalize(document)}><CheckCircle2 size={16} /></button>}{attachment?.file && <a href={attachment.file} target="_blank" rel="noreferrer" title="Apri PDF"><FileUp size={16} /></a>}</div></div>; })}</article>
    {reviewAnalysis && review && <div className="ocr-review-layer" role="dialog" aria-modal="true"><button className="ocr-review-backdrop" aria-label="Chiudi" onClick={closeReview} /><section className="ocr-review-modal"><header><div><p className="eyebrow">Proposta OCR</p><h3>Controlla gli articoli della fattura</h3><span>Includi solo le righe corrette e, se vuoi, collegale a un articolo del catalogo.</span></div><button type="button" title="Chiudi" onClick={closeReview}><X size={20} /></button></header><div className="ocr-review-summary"><label>Fornitore<input value={review.supplier_name} onChange={(event) => updateReview("supplier_name", event.target.value)} /></label><label>Numero fattura<input value={review.invoice_number} onChange={(event) => updateReview("invoice_number", event.target.value)} /></label><label>Data<input type="date" value={review.invoice_date} onChange={(event) => updateReview("invoice_date", event.target.value)} /></label><label>Imponibile articoli<input readOnly value={money(reviewSubtotal)} /></label><label>IVA<input inputMode="decimal" value={review.tax_amount} onChange={(event) => updateReview("tax_amount", event.target.value)} /></label><label>Totale fattura<input readOnly value={money(reviewTotal)} /></label></div><div className="ocr-review-lines"><div className="ocr-review-heading"><span>Incl.</span><span>Descrizione</span><span>Articolo in catalogo</span><span>Qta</span><span>Prezzo</span><span>Totale</span></div>{review.items.length ? review.items.map((item, index) => <div className={`ocr-review-line${item.accepted ? "" : " is-discarded"}`} key={index}><label><input type="checkbox" checked={item.accepted} onChange={(event) => updateItem(index, "accepted", event.target.checked)} /><span className="sr-only">Includi articolo</span></label><input value={item.description} onChange={(event) => updateItem(index, "description", event.target.value)} /><select value={item.variant_id} onChange={(event) => updateItem(index, "variant_id", event.target.value)}><option value="">Non associare ora</option>{variants.map((variant) => <option value={variant.id} key={variant.id}>{variant.product_name || "Articolo"} · {variant.sku}</option>)}</select><input inputMode="numeric" value={item.quantity} onChange={(event) => updateItem(index, "quantity", event.target.value)} /><input inputMode="decimal" value={item.unit_price} onChange={(event) => updateItem(index, "unit_price", event.target.value)} /><input readOnly value={money(lineTotal(item))} /></div>) : <p className="ocr-review-empty">L’OCR non ha riconosciuto righe articolo in questo PDF.</p>}</div><footer><p>Confermare salva questa proposta, ma non aggiorna automaticamente il magazzino.</p><span><button type="button" className="secondary-action" onClick={closeReview}>Scarta modifiche</button><button className="primary-action" disabled={reviewSaving} onClick={saveReview}>{reviewSaving ? "Salvataggio..." : "Conferma proposta"}</button></span></footer></section></div>}
  </section>;
}
