import { useEffect, useState } from "react";
import { CalendarHeart, Download, Plus, Search, Trash2, X } from "lucide-react";
import { request } from "../api";
import "../products.css";

const list = (data) => data?.results || data || [];
const emptyForm = { title: "", beneficiary_first_name: "", beneficiary_last_name: "", list_type: "BIRTH", mode: "PRODUCTS", event_date: "", contact_phone: "", contact_email: "", customer: "", location: "", notifications_enabled: false, notes: "" };
const typeLabel = { BIRTH: "Lista nascita", BIRTHDAY: "Lista compleanno" };
const modeLabel = { PRODUCTS: "Articoli", CONTRIBUTIONS: "Contributi" };
const statusLabel = { OPEN: "Aperta", CLOSED: "Chiusa", CANCELLED: "Annullata" };

export default function GiftListsPage() {
  const [lists, setLists] = useState([]); const [customers, setCustomers] = useState([]); const [locations, setLocations] = useState([]);
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("OPEN"); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState(emptyForm);
  const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false); const [saving, setSaving] = useState(false); const [selected, setSelected] = useState([]);
  const load = async (search = query, selectedStatus = status) => { try { const params = new URLSearchParams(); if (search.trim()) params.set("search", search.trim()); if (selectedStatus !== "ALL") params.set("status", selectedStatus); const [giftData, customerData, locationData] = await Promise.all([request(`/gift-lists/lists/?${params}`), request("/customers/customers/"), request("/core/locations/")]); setLists(list(giftData)); setCustomers(list(customerData)); setLocations(list(locationData)); } catch (error) { setSuccess(false); setMessage(error.message); } };
  useEffect(() => { load("", "OPEN"); }, []);
  useEffect(() => { if (!message) return undefined; const timer = setTimeout(() => setMessage(""), 4000); return () => clearTimeout(timer); }, [message]);
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  const openCreate = () => { setForm({ ...emptyForm, location: locations[0]?.id || "" }); setMessage(""); setFormOpen(true); };
  async function createList(event) { event.preventDefault(); setSaving(true); setMessage(""); try { const payload = { ...form, code: `LIST-${Date.now()}`, customer: form.customer || null, event_date: form.event_date || null }; await request("/gift-lists/lists/", { method: "POST", body: JSON.stringify(payload) }); if (form.notifications_enabled && form.event_date) await request("/gift-lists/lists/refresh-notifications/", { method: "POST", body: JSON.stringify({}) }); setFormOpen(false); setForm(emptyForm); setSuccess(true); setMessage("Lista regalo creata correttamente."); setStatus("OPEN"); await load("", "OPEN"); } catch (error) { setSuccess(false); setMessage(error.message); } finally { setSaving(false); } }
  const toggleSelected = (id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const toggleAll = () => setSelected(selected.length === lists.length ? [] : lists.map((item) => item.id));
  const csv = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;
  function downloadSelected() { const rows = lists.filter((item) => selected.includes(item.id)); const content = [["Codice", "Titolo", "Beneficiario", "Tipo", "Modalità", "Evento", "Stato"], ...rows.map((item) => [item.code, item.title, `${item.beneficiary_first_name} ${item.beneficiary_last_name}`, typeLabel[item.list_type], modeLabel[item.mode], item.event_date || "", statusLabel[item.status]])].map((row) => row.map(csv).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); link.download = "liste-regalo.csv"; link.click(); URL.revokeObjectURL(link.href); }
  async function deleteSelected() { try { await Promise.all(selected.map((id) => request(`/gift-lists/lists/${id}/`, { method: "DELETE" }))); setSelected([]); setSuccess(true); setMessage("Liste regalo eliminate correttamente."); await load(); } catch (error) { setSuccess(false); setMessage(error.message); } }
  async function closeList(item) { try { const result = await request(`/gift-lists/lists/${item.id}/close/`, { method: "POST", body: JSON.stringify({}) }); setSuccess(true); setMessage(result.voucher ? `Lista chiusa: generato il buono ${result.voucher.code}.` : "Lista regalo chiusa correttamente."); await load(); } catch (error) { setSuccess(false); setMessage(error.message); } }
  const date = (value) => value ? new Intl.DateTimeFormat("it-IT").format(new Date(`${value}T00:00:00`)) : "Non indicata";
  return <section className="products-page gift-lists-page">
    <style>{`.gift-list-form{display:grid;grid-template-columns:1.25fr repeat(3,minmax(130px,1fr));gap:14px;align-items:end;padding:20px;border-radius:14px;background:#fff;box-shadow:0 7px 22px #25171a09}.gift-list-form label{display:grid;gap:6px;font-size:11px;font-weight:900}.gift-list-form input,.gift-list-form select{box-sizing:border-box;width:100%;height:42px;border:1px solid #ded9db;border-radius:8px;padding:0 10px;background:#fff;font:inherit}.gift-list-form .gift-list-copy{grid-row:span 2}.gift-list-form .gift-list-notes{grid-column:2/4}.gift-list-form label.notification-control{display:flex;align-items:center;gap:10px;min-height:42px;padding:0 12px;border:1px solid #ded9db;border-radius:8px;background:#fff;font-size:12px;cursor:pointer}.gift-list-form .notification-control input{width:18px;height:18px;margin:0;padding:0;accent-color:#ed001b;cursor:pointer}.gift-list-filters{display:flex;align-items:center;justify-content:space-between;gap:16px}.gift-status-tabs{display:flex;gap:5px}.gift-status-tabs button{height:34px;border:0;border-radius:7px;padding:0 10px;background:transparent;color:#777176;font-size:11px;font-weight:800;cursor:pointer}.gift-status-tabs button.active{background:#18151a;color:#fff}.gift-list-heading,.gift-list-row{display:grid;grid-template-columns:minmax(190px,1.3fr) minmax(130px,.8fr) 125px 130px 90px;align-items:center;gap:18px;padding:15px 22px}.gift-list-heading{color:#8b858a;font-size:10px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}.gift-list-row{border-top:1px solid #eeeaea}.gift-list-row>div{display:grid;gap:4px}.gift-list-row strong{font-size:13px}.gift-list-row span{color:#817b80;font-size:12px}.gift-status{justify-self:start;padding:5px 8px;border-radius:7px;background:#edf9f1;color:#167444;font-size:10px;font-style:normal;font-weight:900}.gift-status.closed{background:#f1eff0;color:#625b60}.gift-status.cancelled{background:#fff0f2;color:#b00019}@media(max-width:900px){.gift-list-form{grid-template-columns:1fr 1fr}.gift-list-form .gift-list-copy{grid-column:1/-1;grid-row:auto}.gift-list-form .gift-list-notes{grid-column:auto}}@media(max-width:640px){.gift-list-form{grid-template-columns:1fr}.gift-list-filters{align-items:stretch;flex-direction:column}.gift-status-tabs{overflow-x:auto;padding-bottom:2px}.gift-list-heading{display:none}.gift-list-row{grid-template-columns:1fr auto;padding:16px}.gift-list-row>span{display:none}.gift-status{grid-column:2;grid-row:1}.gift-list-form .inline-form-actions button{flex:1}}`}</style>
    <style>{`.gift-selection-actions{display:flex;align-items:center;justify-content:flex-end;gap:10px;color:#716a70;font-size:12px;font-weight:800}.gift-selection-actions button{display:flex;align-items:center;gap:7px;height:38px;border:1px solid #e2dddf;border-radius:8px;padding:0 12px;background:#fff;color:#403a3f;font:inherit;cursor:pointer}.gift-selection-actions .delete-selected{border:0;background:#ed001b;color:#fff}.gift-list-heading,.gift-list-row{grid-template-columns:34px minmax(190px,1.3fr) minmax(130px,.8fr) 125px 130px 90px 105px}.gift-list-check{display:grid!important;place-items:center}.gift-list-check input{width:17px;height:17px;accent-color:#178c82;cursor:pointer}.gift-list-row.selected{background:#edf8f7}.gift-list-actions{display:flex!important;justify-content:flex-end}.gift-list-actions button{height:32px;border:1px solid #e2dddf;border-radius:7px;padding:0 10px;background:#fff;color:#403a3f;font-size:11px;font-weight:800;cursor:pointer}.gift-list-actions button:hover{border-color:#ed001b;color:#b70018}@media(max-width:760px){.gift-selection-actions{justify-content:flex-start;flex-wrap:wrap}.gift-list-heading{display:none}.gift-list-row{grid-template-columns:28px 1fr auto}.gift-list-row>span{display:none}.gift-list-check{grid-column:1;grid-row:1}.gift-list-row>div:nth-child(2){grid-column:2;grid-row:1}.gift-status{grid-column:3;grid-row:1}.gift-list-actions{grid-column:2/-1;grid-row:2;justify-content:flex-start!important}}`}</style>
    <div className="page-title-row"><div><p className="eyebrow">Clienti</p><h2>Liste regalo</h2><span>Liste nascita e compleanno con articoli riservati o contributi da trasformare in buono.</span></div><button className="primary-action" onClick={openCreate}><Plus size={17} /> Nuova lista</button></div>
    {formOpen && <form className="gift-list-form" onSubmit={createList}><div className="inventory-form-copy gift-list-copy"><p className="eyebrow">Nuova lista</p><h3>Crea una lista regalo</h3><span>Una lista articoli riserva i capi; una lista contributi genera un buono alla chiusura.</span></div><label>Titolo lista<input required value={form.title} onChange={(event) => update("title", event.target.value)} placeholder="Es. Lista nascita Rossi" /></label><label>Nome beneficiario<input required value={form.beneficiary_first_name} onChange={(event) => update("beneficiary_first_name", event.target.value)} /></label><label>Cognome beneficiario<input required value={form.beneficiary_last_name} onChange={(event) => update("beneficiary_last_name", event.target.value)} /></label><label>Tipo<select value={form.list_type} onChange={(event) => { update("list_type", event.target.value); if (event.target.value === "BIRTH") update("mode", "PRODUCTS"); }}><option value="BIRTH">Lista nascita</option><option value="BIRTHDAY">Lista compleanno</option></select></label><label>Modalità<select value={form.mode} disabled={form.list_type === "BIRTH"} onChange={(event) => update("mode", event.target.value)}><option value="PRODUCTS">Articoli</option><option value="CONTRIBUTIONS">Contributi</option></select></label><label>Sede<select required value={form.location} onChange={(event) => update("location", event.target.value)}><option value="">Seleziona sede</option>{locations.map((location) => <option key={location.id} value={location.id}>{location.name}</option>)}</select></label><label>Data evento<input type="date" value={form.event_date} onChange={(event) => update("event_date", event.target.value)} /></label><label>Cliente registrato<select value={form.customer} onChange={(event) => update("customer", event.target.value)}><option value="">Non associare un cliente</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.full_name}</option>)}</select></label><label>Telefono<input value={form.contact_phone} onChange={(event) => update("contact_phone", event.target.value)} /></label><label>Email<input type="email" value={form.contact_email} onChange={(event) => update("contact_email", event.target.value)} /></label><label className="notification-control"><input type="checkbox" checked={form.notifications_enabled} onChange={(event) => update("notifications_enabled", event.target.checked)} /><span>Avvisami per questa lista</span></label><label className="gift-list-notes">Note<input value={form.notes} onChange={(event) => update("notes", event.target.value)} placeholder="Facoltative" /></label><div className="inline-form-actions"><button type="button" className="secondary-action" onClick={() => setFormOpen(false)}><X size={17} /> Annulla</button><button className="primary-action" disabled={saving}>{saving ? "Creazione..." : "Crea lista"}</button></div></form>}
    {message && <p className={success ? "operation-success" : "catalog-error"}>{message}</p>}
    <div className="gift-list-filters"><form className="products-search" onSubmit={(event) => { event.preventDefault(); load(); }}><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cerca lista o beneficiario" /><button>Ricerca</button></form><div className="gift-status-tabs">{[["OPEN", "Aperte"], ["CLOSED", "Chiuse"], ["CANCELLED", "Annullate"], ["ALL", "Tutte"]].map(([value, label]) => <button type="button" key={value} className={status === value ? "active" : ""} onClick={() => { setStatus(value); load(query, value); }}>{label}</button>)}</div></div>
    {selected.length > 0 && <div className="gift-selection-actions"><span>{selected.length} {selected.length === 1 ? "lista selezionata" : "liste selezionate"}</span><button type="button" onClick={() => setSelected([])}>Deseleziona</button><button type="button" onClick={downloadSelected}><Download size={16} /> Scarica CSV</button><button type="button" className="delete-selected" onClick={deleteSelected}><Trash2 size={16} /> Elimina</button></div>}
    <article className="products-list"><div className="gift-list-heading"><span className="gift-list-check"><input type="checkbox" aria-label="Seleziona tutte le liste" checked={lists.length > 0 && selected.length === lists.length} onChange={toggleAll} /></span><span>Lista</span><span>Beneficiario</span><span>Modalità</span><span>Evento</span><span>Stato</span><span>Azioni</span></div>{!lists.length ? <div className="empty-product-state"><CalendarHeart size={28} /><strong>Nessuna lista regalo trovata</strong><span>Crea una lista nascita o compleanno per iniziare.</span></div> : lists.map((giftList) => <div className={selected.includes(giftList.id) ? "gift-list-row selected" : "gift-list-row"} key={giftList.id}><span className="gift-list-check"><input type="checkbox" aria-label={`Seleziona ${giftList.title}`} checked={selected.includes(giftList.id)} onChange={() => toggleSelected(giftList.id)} /></span><div><strong>{giftList.title}</strong><span>{giftList.code} · {typeLabel[giftList.list_type]}</span></div><span>{giftList.beneficiary_first_name} {giftList.beneficiary_last_name}</span><span>{modeLabel[giftList.mode]}</span><span>{date(giftList.event_date)}</span><em className={`gift-status ${giftList.status.toLowerCase()}`}>{statusLabel[giftList.status]}</em><div className="gift-list-actions">{giftList.status === "OPEN" && <button type="button" onClick={() => closeList(giftList)}>Chiudi lista</button>}</div></div>)}</article>
  </section>;
}
