import { useEffect, useMemo, useState } from "react";
import { Archive, Bell, CheckCheck, CircleAlert, Search } from "lucide-react";
import { request } from "../api";
import "../products.css";

const list = (data) => data?.results || data || [];
const typeLabel = { STOCK_DEPLETED: "Scorte", REORDER: "Riordini", VOUCHER_EXPIRING: "Buoni", EXPENSE_DUE: "Spese", GIFT_LIST: "Liste regalo", SYSTEM: "Sistema" };
const priorityLabel = { LOW: "Bassa", NORMAL: "Normale", HIGH: "Alta", CRITICAL: "Critica" };
const target = { "expenses.Expense": "Spese", "reorders.ReorderItem": "Riordini", "vouchers.Voucher": "Buoni", "giftlists.GiftList": "Liste regalo" };

export default function NotificationsPage({ onNavigate }) {
  const [notifications, setNotifications] = useState([]); const [deliveries, setDeliveries] = useState([]); const [selected, setSelected] = useState([]); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("ACTIVE"); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false);
  const notice = (text, ok = true) => { setSuccess(ok); setMessage(text); };
  const load = async () => { try { const [notificationData, deliveryData] = await Promise.all([request("/notifications/notifications/"), request("/notifications/deliveries/")]); setNotifications(list(notificationData)); setDeliveries(list(deliveryData)); } catch (error) { notice(error.message, false); } };
  useEffect(() => { load(); }, []);
  useEffect(() => { if (!message) return undefined; const timer = setTimeout(() => setMessage(""), 4000); return () => clearTimeout(timer); }, [message]);
  const deliveryFor = (id) => deliveries.find((item) => item.notification === id);
  const items = useMemo(() => notifications.filter((item) => { const delivery = deliveryFor(item.id); const text = `${item.title} ${item.message}`.toLowerCase(); return (!query.trim() || text.includes(query.toLowerCase())) && (filter === "ALL" || item.status === filter) && !delivery?.archived_at; }), [notifications, deliveries, query, filter]);
  async function markRead(delivery) { if (!delivery || delivery.read_at) return; try { await request(`/notifications/deliveries/${delivery.id}/mark-read/`, { method: "POST", body: JSON.stringify({}) }); await load(); } catch (error) { notice(error.message, false); } }
  async function resolve(item) { try { await request(`/notifications/notifications/${item.id}/resolve/`, { method: "POST", body: JSON.stringify({ notes: "Risolta dalla pagina notifiche." }) }); notice("Notifica risolta correttamente."); await load(); } catch (error) { notice(error.message, false); } }
  async function archive(delivery) { try { await request(`/notifications/deliveries/${delivery.id}/archive/`, { method: "POST", body: JSON.stringify({}) }); notice("Notifica archiviata."); await load(); } catch (error) { notice(error.message, false); } }
  const toggle = (id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const toggleAll = () => setSelected(selected.length === items.length ? [] : items.map((item) => item.id));
  async function archiveSelected() { const selectedDeliveries = items.filter((item) => selected.includes(item.id)).map((item) => deliveryFor(item.id)).filter(Boolean); if (!selectedDeliveries.length) return; try { await Promise.all(selectedDeliveries.map(archive)); setSelected([]); } catch { /* archive already reports the error */ } }
  const openSource = (item) => { const page = target[item.source_type]; if (page) onNavigate?.(page); };
  const date = (value) => new Intl.DateTimeFormat("it-IT", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

  return <section className="products-page notifications-page"><style>{`.notification-summary{display:grid;grid-template-columns:repeat(2,minmax(0,220px));gap:13px}.notification-summary article{display:flex;align-items:center;gap:12px;padding:16px;border-radius:12px;background:#fff;box-shadow:0 7px 22px #25171a09}.notification-summary svg{color:#c70019}.notification-summary div{display:grid;gap:3px}.notification-summary span,.notification-row span{color:#817b80;font-size:12px}.notification-summary strong{font-size:21px}.notification-heading,.notification-row{display:grid;grid-template-columns:34px minmax(190px,1.3fr) 105px 100px minmax(180px,.9fr) 158px;align-items:center;gap:18px;padding:15px 22px}.notification-heading{color:#8b858a;font-size:10px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}.notification-row{border-top:1px solid #eeeaea}.notification-row.selected{background:#edf8f7}.notification-row.unread{background:#fff9fa}.notification-row>div{display:grid;gap:4px}.notification-row strong{font-size:13px}.notification-check{display:grid!important;place-items:center}.notification-check input{width:17px;height:17px;accent-color:#178c82;cursor:pointer}.notification-priority{justify-self:start;padding:5px 8px;border-radius:7px;background:#f1eff0;color:#6f676c;font-size:10px;font-style:normal;font-weight:900}.notification-priority.high,.notification-priority.critical{background:#fff0f2;color:#b00019}.notification-actions{display:flex!important;justify-content:flex-end;gap:7px}.notification-actions button{display:grid;width:33px;height:33px;place-items:center;border:1px solid #e2dddf;border-radius:7px;background:#fff;color:#4d464c;cursor:pointer}.notification-actions button:hover{border-color:#ed001b;color:#b70018}.notification-actions button:disabled{opacity:.45;cursor:default}@media(max-width:800px){.notification-heading{display:none}.notification-row{grid-template-columns:28px 1fr auto;padding:16px}.notification-row>span,.notification-row>em{display:none}.notification-check{grid-column:1;grid-row:1}.notification-row>div:nth-child(2){grid-column:2}.notification-actions{grid-column:3;grid-row:1}.notification-summary{grid-template-columns:1fr 1fr}.voucher-filters{align-items:stretch;flex-direction:column}.status-tabs{overflow-x:auto;white-space:nowrap}}`}</style>
    <div className="page-title-row"><div><p className="eyebrow">Gestione</p><h2>Notifiche</h2><span>Avvisi personali su scadenze, scorte, riordini e operazioni da gestire.</span></div></div>
    <section className="notification-summary"><article><Bell size={20} /><div><span>Avvisi attivi</span><strong>{notifications.filter((item) => item.status === "ACTIVE").length}</strong></div></article><article><CircleAlert size={20} /><div><span>Priorità alta</span><strong>{notifications.filter((item) => ["HIGH", "CRITICAL"].includes(item.priority) && item.status === "ACTIVE").length}</strong></div></article></section>
    {message && <p className={success ? "operation-success" : "catalog-error"}>{message}</p>}
    <div className="voucher-filters"><div className="products-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cerca nelle notifiche" /></div><div className="status-tabs">{[["ACTIVE", "Attive"], ["RESOLVED", "Risolte"], ["ALL", "Tutte"]].map(([value, label]) => <button type="button" className={filter === value ? "active" : ""} onClick={() => setFilter(value)} key={value}>{label}</button>)}</div></div>
    {selected.length > 0 && <div className="table-selection-actions"><span>{selected.length} notifiche selezionate</span><button type="button" onClick={() => setSelected([])}>Deseleziona</button><button type="button" className="delete-selected" onClick={archiveSelected}><Archive size={16} /> Elimina</button></div>}
    <article className="products-list"><div className="notification-heading"><span className="notification-check"><input type="checkbox" checked={items.length > 0 && selected.length === items.length} onChange={toggleAll} aria-label="Seleziona tutte le notifiche" /></span><span>Notifica</span><span>Area</span><span>Priorità</span><span>Ricevuta</span><span>Azioni</span></div>{!items.length ? <div className="empty-product-state"><Bell size={28} /><strong>Nessuna notifica trovata</strong><span>Quando ci sarà qualcosa da gestire, comparirà qui.</span></div> : items.map((item) => { const delivery = deliveryFor(item.id); return <div className={`notification-row ${selected.includes(item.id) ? "selected" : ""} ${delivery && !delivery.read_at ? "unread" : ""}`} key={item.id}><span className="notification-check"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => toggle(item.id)} aria-label={`Seleziona ${item.title}`} /></span><div><strong>{item.title}</strong><span>{item.message}</span></div><span>{typeLabel[item.notification_type] || item.notification_type}</span><em className={`notification-priority ${item.priority.toLowerCase()}`}>{priorityLabel[item.priority]}</em><span>{date(item.occurred_at)}</span><div className="notification-actions">{item.source_type && <button type="button" title="Apri elemento collegato" onClick={() => openSource(item)}><Search size={16} /></button>}<button type="button" title="Segna come letta" disabled={!delivery || Boolean(delivery.read_at)} onClick={() => markRead(delivery)}><CheckCheck size={16} /></button>{item.status === "ACTIVE" && <button type="button" title="Risolvi notifica" onClick={() => resolve(item)}><CircleAlert size={16} /></button>}<button type="button" title="Archivia" disabled={!delivery} onClick={() => archive(delivery)}><Archive size={16} /></button></div></div>; })}</article>
  </section>;
}
