import { useEffect, useState } from "react";
import { ClipboardList, Plus, Search, Send, Trash2, X } from "lucide-react";
import { request } from "../api";
import "../products.css";

const list = (data) => data?.results || data || [];
const today = () => new Date().toISOString().slice(0, 10);
const emptyOrder = { supplier: "", order_date: today(), expected_delivery_date: "", notes: "" };
const emptyLine = () => ({ variant: "", quantity_ordered: "1", expected_unit_cost: "" });
const statusLabel = { DRAFT: "Bozza", SENT: "Inviato", PARTIALLY_RECEIVED: "Parzialmente ricevuto", RECEIVED: "Ricevuto", CANCELLED: "Annullato" };

export default function PurchaseOrdersPage() {
  const [orders, setOrders] = useState([]); const [suppliers, setSuppliers] = useState([]); const [variants, setVariants] = useState([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("DRAFT");
  const [formOpen, setFormOpen] = useState(false); const [orderForm, setOrderForm] = useState(emptyOrder); const [lines, setLines] = useState([emptyLine()]); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false);
  const load = async (search = query, selectedStatus = status) => { try { const params = new URLSearchParams(); if (search.trim()) params.set("search", search.trim()); if (selectedStatus !== "ALL") params.set("status", selectedStatus); const [orderData, supplierData, variantData] = await Promise.all([request(`/purchasing/orders/?${params}`), request("/suppliers/suppliers/?is_active=true"), request("/catalog/variants/?page_size=200")]); setOrders(list(orderData)); setSuppliers(list(supplierData)); setVariants(list(variantData)); } catch (error) { setSuccess(false); setMessage(error.message); } };
  useEffect(() => { load("", "DRAFT"); }, []);
  useEffect(() => { if (!message) return undefined; const timer = setTimeout(() => setMessage(""), 4000); return () => clearTimeout(timer); }, [message]);
  const updateOrder = (field, value) => setOrderForm((current) => ({ ...current, [field]: value }));
  const updateLine = (index, field, value) => setLines((current) => current.map((line, lineIndex) => lineIndex === index ? { ...line, [field]: value } : line));
  const openCreate = () => { setOrderForm(emptyOrder); setLines([emptyLine()]); setMessage(""); setFormOpen(true); };
  async function createOrder(event) { event.preventDefault(); const validLines = lines.filter((line) => line.variant && Number(line.quantity_ordered) > 0); if (!validLines.length) return setMessage("Aggiungi almeno un articolo all'ordine."); setSaving(true); setMessage(""); try { const order = await request("/purchasing/orders/", { method: "POST", body: JSON.stringify({ ...orderForm, number: `OA-${Date.now()}`, expected_delivery_date: orderForm.expected_delivery_date || null }) }); await Promise.all(validLines.map((line) => request("/purchasing/order-lines/", { method: "POST", body: JSON.stringify({ order: order.id, variant: line.variant, quantity_ordered: Number(line.quantity_ordered), expected_unit_cost: line.expected_unit_cost || null }) }))); setFormOpen(false); setSuccess(true); setMessage("Ordine in bozza creato correttamente."); setStatus("DRAFT"); await load("", "DRAFT"); } catch (error) { setSuccess(false); setMessage(error.message); } finally { setSaving(false); } }
  async function sendOrder(order) { try { await request(`/purchasing/orders/${order.id}/send/`, { method: "POST", body: JSON.stringify({}) }); setSuccess(true); setMessage("Ordine inviato al fornitore."); await load(); } catch (error) { setSuccess(false); setMessage(error.message); } }
  const supplierName = (id) => suppliers.find((supplier) => supplier.id === id)?.business_name || id;
  const date = (value) => value ? new Intl.DateTimeFormat("it-IT").format(new Date(`${value}T00:00:00`)) : "Non indicata";
  return <section className="products-page purchase-orders-page">
    <style>{`.purchase-order-form{display:grid;grid-template-columns:1.3fr 1fr 1fr;gap:14px;align-items:end;padding:20px;border-radius:14px;background:#fff;box-shadow:0 7px 22px #25171a09}.purchase-order-form label{display:grid;gap:6px;font-size:11px;font-weight:900}.purchase-order-form input,.purchase-order-form select{box-sizing:border-box;width:100%;height:42px;border:1px solid #ded9db;border-radius:8px;padding:0 10px;background:#fff;font:inherit}.purchase-order-copy{grid-row:span 2}.order-lines-editor{grid-column:2/-1;display:grid;gap:8px}.order-lines-editor>span{font-size:11px;font-weight:900}.order-line-editor{display:grid;grid-template-columns:minmax(0,1fr) 110px 130px 34px;gap:8px}.order-line-editor button{display:grid;place-items:center;border:1px solid #e2dddf;border-radius:7px;background:#fff;color:#b70018;cursor:pointer}.add-order-line{justify-self:start;border:0;background:transparent;color:#b70018;font-size:12px;font-weight:900;cursor:pointer}.order-form-actions{grid-column:2/-1;display:flex;justify-content:flex-end;gap:8px}.order-heading,.order-row{display:grid;grid-template-columns:minmax(160px,1fr) minmax(180px,1fr) 140px 150px 110px;align-items:center;gap:18px;padding:15px 22px}.order-heading{color:#8b858a;font-size:10px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}.order-row{border-top:1px solid #eeeaea}.order-row>div{display:grid;gap:4px}.order-row strong{font-size:13px}.order-row span{color:#817b80;font-size:12px}.order-status{justify-self:start;padding:5px 8px;border-radius:7px;background:#fff3d9;color:#a56800;font-size:10px;font-style:normal;font-weight:900}.order-status.sent,.order-status.partially_received{background:#edf3ff;color:#3762aa}.order-status.received{background:#edf9f1;color:#167444}.order-status.cancelled{background:#fff0f2;color:#b00019}.order-send{justify-self:start;height:33px;border:0;border-radius:7px;padding:0 11px;background:#ed001b;color:#fff;font-size:11px;font-weight:900;cursor:pointer}@media(max-width:800px){.purchase-order-form{grid-template-columns:1fr 1fr}.purchase-order-copy,.order-lines-editor,.order-form-actions{grid-column:1/-1;grid-row:auto}.order-heading{display:none}.order-row{grid-template-columns:1fr auto;padding:16px}.order-row>span{display:none}.order-status{grid-column:2;grid-row:1}.order-send{grid-column:1;grid-row:2}}@media(max-width:560px){.purchase-order-form{grid-template-columns:1fr}.order-line-editor{grid-template-columns:1fr 86px 105px 34px}.order-form-actions button{flex:1}}`}</style>
    <style>{`.purchase-order-page .voucher-filters{display:flex;align-items:center;justify-content:space-between;gap:16px}.purchase-order-page .status-tabs{display:flex;align-items:center;gap:5px}.purchase-order-page .status-tabs button{height:34px;border:0;border-radius:7px;padding:0 10px;background:transparent;color:#777176;font-size:11px;font-weight:800;cursor:pointer}.purchase-order-page .status-tabs button.active{background:#18151a;color:#fff}@media(max-width:760px){.purchase-order-page .voucher-filters{align-items:stretch;flex-direction:column}.purchase-order-page .status-tabs{overflow-x:auto;padding-bottom:2px}}`}</style>
    <div className="page-title-row"><div><p className="eyebrow">Acquisti</p><h2>Ordini acquisto</h2><span>Prepara bozze, inviale ai fornitori e segui la consegna della merce.</span></div><button className="primary-action" onClick={openCreate}><Plus size={17} /> Nuovo ordine</button></div>
    {formOpen && <form className="purchase-order-form" onSubmit={createOrder}><div className="inventory-form-copy purchase-order-copy"><p className="eyebrow">Nuovo ordine</p><h3>Prepara una bozza</h3><span>Scegli fornitore e articoli, poi invia l’ordine quando è completo.</span></div><label>Fornitore<select required value={orderForm.supplier} onChange={(event) => updateOrder("supplier", event.target.value)}><option value="">Seleziona fornitore</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.business_name}</option>)}</select></label><label>Data ordine<input required type="date" value={orderForm.order_date} onChange={(event) => updateOrder("order_date", event.target.value)} /></label><label>Consegna prevista<input type="date" value={orderForm.expected_delivery_date} onChange={(event) => updateOrder("expected_delivery_date", event.target.value)} /></label><label>Note<input value={orderForm.notes} onChange={(event) => updateOrder("notes", event.target.value)} placeholder="Facoltative" /></label><div className="order-lines-editor"><span>Articoli ordinati</span>{lines.map((line, index) => <div className="order-line-editor" key={index}><select required value={line.variant} onChange={(event) => updateLine(index, "variant", event.target.value)}><option value="">Seleziona articolo / SKU</option>{variants.map((variant) => <option key={variant.id} value={variant.id}>{variant.product_name || "Articolo"} · {variant.sku}</option>)}</select><input required min="1" type="number" value={line.quantity_ordered} onChange={(event) => updateLine(index, "quantity_ordered", event.target.value)} title="Quantità" /><input min="0" step="0.0001" type="number" value={line.expected_unit_cost} onChange={(event) => updateLine(index, "expected_unit_cost", event.target.value)} placeholder="Costo unit." />{lines.length > 1 ? <button type="button" onClick={() => setLines((current) => current.filter((_, lineIndex) => lineIndex !== index))} title="Rimuovi riga"><Trash2 size={15} /></button> : <span />}</div>)}<button className="add-order-line" type="button" onClick={() => setLines((current) => [...current, emptyLine()])}><Plus size={15} /> Aggiungi riga</button></div><div className="order-form-actions"><button type="button" className="secondary-action" onClick={() => setFormOpen(false)}><X size={17} /> Annulla</button><button className="primary-action" disabled={saving}>{saving ? "Creazione..." : "Crea bozza"}</button></div></form>}
    {message && <p className={success ? "operation-success" : "catalog-error"}>{message}</p>}
    <div className="voucher-filters"><form className="products-search" onSubmit={(event) => { event.preventDefault(); load(); }}><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cerca numero ordine o note" /><button>Ricerca</button></form><div className="status-tabs">{[["DRAFT", "Bozze"], ["SENT", "Inviati"], ["PARTIALLY_RECEIVED", "Parziali"], ["RECEIVED", "Ricevuti"], ["ALL", "Tutti"]].map(([value, label]) => <button type="button" className={status === value ? "active" : ""} key={value} onClick={() => { setStatus(value); load(query, value); }}>{label}</button>)}</div></div>
    <article className="products-list"><div className="order-heading"><span>Ordine</span><span>Fornitore</span><span>Data ordine</span><span>Consegna prevista</span><span>Stato</span></div>{!orders.length ? <div className="empty-product-state"><ClipboardList size={28} /><strong>Nessun ordine trovato</strong><span>Crea una bozza per iniziare un nuovo acquisto.</span></div> : orders.map((order) => <div className="order-row" key={order.id}><div><strong>{order.number}</strong><span>{order.notes || "Nessuna nota"}</span></div><span>{supplierName(order.supplier)}</span><span>{date(order.order_date)}</span><span>{date(order.expected_delivery_date)}</span>{order.status === "DRAFT" ? <button className="order-send" onClick={() => sendOrder(order)}><Send size={14} /> Invia</button> : <em className={`order-status ${order.status.toLowerCase()}`}>{statusLabel[order.status] || order.status}</em>}</div>)}</article>
  </section>;
}
