import { useEffect, useMemo, useState } from "react";
import { CalendarDays, ChevronDown, Download, Filter, Search, ShoppingBag, X } from "lucide-react";
import { downloadFile, request } from "../api";
import "../sales.css";

const euro = new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR" });
const dateFormatter = new Intl.DateTimeFormat("it-IT", { day: "2-digit", month: "short", year: "numeric", hour: "2-digit", minute: "2-digit" });
const initialFilters = { search: "", status: "ALL", dateFrom: "", dateTo: "", brand: "", category: "", season: "", location: "", cashRegister: "", channel: "", paymentMethod: "" };

function listItems(payload) { return payload?.results || payload || []; }
function asInputDate(date) { return date.toLocaleDateString("en-CA"); }
function periodRange(preset) {
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const startOfWeek = new Date(today); startOfWeek.setDate(today.getDate() - ((today.getDay() + 6) % 7));
  if (preset === "TODAY") return [today, today];
  if (preset === "YESTERDAY") { const day = new Date(today); day.setDate(day.getDate() - 1); return [day, day]; }
  if (preset === "LAST_7") { const start = new Date(today); start.setDate(start.getDate() - 6); return [start, today]; }
  if (preset === "CURRENT_WEEK") return [startOfWeek, today];
  if (preset === "PREVIOUS_WEEK") { const end = new Date(startOfWeek); end.setDate(end.getDate() - 1); const start = new Date(end); start.setDate(start.getDate() - 6); return [start, end]; }
  if (preset === "CURRENT_MONTH") return [new Date(today.getFullYear(), today.getMonth(), 1), today];
  return [new Date(today.getFullYear(), today.getMonth() - 1, 1), new Date(today.getFullYear(), today.getMonth(), 0)];
}
function SelectField({ label, value, onChange, options }) {
  return <label className="history-filter-field"><span>{label}</span><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">Tutti</option>{options.map((option) => <option key={option.id || option.value} value={option.id || option.value}>{option.name || option.label}</option>)}</select></label>;
}

export default function SalesPage({ onStartReturn }) {
  const [filters, setFilters] = useState(initialFilters); const [sales, setSales] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [periodOpen, setPeriodOpen] = useState(false); const [filtersOpen, setFiltersOpen] = useState(false); const [periodDraft, setPeriodDraft] = useState({ dateFrom: "", dateTo: "", preset: "" });
  const [options, setOptions] = useState({ brands: [], categories: [], seasons: [], locations: [], registers: [] });
  const query = useMemo(() => { const params = new URLSearchParams({ ordering: "-opened_at" }); const fields = { search: "search", status: "status", dateFrom: "date_from", dateTo: "date_to", brand: "brand", category: "category", season: "season", location: "location", cashRegister: "cash_register", channel: "channel", paymentMethod: "payment_method" }; Object.entries(fields).forEach(([key, parameter]) => { if (filters[key] && filters[key] !== "ALL") params.set(parameter, filters[key]); }); return params.toString(); }, [filters]);
  useEffect(() => { setLoading(true); setError(""); request(`/sales/sales/?${query}`).then((payload) => setSales(listItems(payload))).catch(() => setError("Non è stato possibile caricare lo storico vendite.")).finally(() => setLoading(false)); }, [query]);
  useEffect(() => { Promise.all([request("/catalog/brands/?active=true"), request("/catalog/categories/?active=true"), request("/catalog/seasons/?active=true"), request("/core/locations/?active=true"), request("/sales/registers/")]).then(([brands, categories, seasons, locations, registers]) => setOptions({ brands: listItems(brands), categories: listItems(categories), seasons: listItems(seasons), locations: listItems(locations), registers: listItems(registers) })).catch(() => {}); }, []);
  function updateFilter(key, value) { setFilters((current) => ({ ...current, [key]: value })); }
  function setPreset(preset) { const [from, to] = periodRange(preset); setPeriodDraft({ dateFrom: asInputDate(from), dateTo: asInputDate(to), preset }); }
  function applyPeriod() { setFilters((current) => ({ ...current, dateFrom: periodDraft.dateFrom, dateTo: periodDraft.dateTo })); setPeriodOpen(false); }
  function clearPeriod() { setPeriodDraft({ dateFrom: "", dateTo: "", preset: "" }); setFilters((current) => ({ ...current, dateFrom: "", dateTo: "" })); setPeriodOpen(false); }
  async function exportCsv() { try { await downloadFile(`/sales/sales/export-csv/?${query}`, "vendite.csv"); } catch (downloadError) { setError(downloadError.message); } }
  return <section className="sales-page history-page">
    <div className="page-title-row"><div><p className="eyebrow">Operatività</p><h2>Storico vendite</h2><span>Ricerca gli scontrini e apri una vendita per avviare un reso.</span></div><button className="secondary-action csv-button" onClick={exportCsv}><Download size={17} /> Scarica CSV</button></div>
    <div className="history-toolbar"><label className="sales-search"><Search size={18} /><input value={filters.search} onChange={(event) => updateFilter("search", event.target.value)} placeholder="Cerca scontrino, cliente, marca, SKU o barcode" /></label><button className={`history-tool-button ${filters.dateFrom || filters.dateTo ? "active" : ""}`} onClick={() => { setPeriodDraft({ dateFrom: filters.dateFrom, dateTo: filters.dateTo, preset: "" }); setPeriodOpen(true); }}><CalendarDays size={17} /> Periodo <ChevronDown size={15} /></button><button className={`history-tool-button ${filtersOpen ? "active" : ""}`} onClick={() => setFiltersOpen((open) => !open)}><Filter size={17} /> Filtri <ChevronDown size={15} /></button></div>
    {filtersOpen && <div className="history-filters-panel"><SelectField label="Stato" value={filters.status === "ALL" ? "" : filters.status} onChange={(value) => updateFilter("status", value || "ALL")} options={[{ value: "OPEN", label: "Aperte" }, { value: "CONFIRMED", label: "Concluse" }, { value: "CANCELLED", label: "Annullate" }]} /><SelectField label="Canale" value={filters.channel} onChange={(value) => updateFilter("channel", value)} options={[{ value: "POS", label: "Negozio" }, { value: "SHOPIFY", label: "Shopify" }]} /><SelectField label="Sede" value={filters.location} onChange={(value) => updateFilter("location", value)} options={options.locations} /><SelectField label="Cassa" value={filters.cashRegister} onChange={(value) => updateFilter("cashRegister", value)} options={options.registers} /><SelectField label="Marca" value={filters.brand} onChange={(value) => updateFilter("brand", value)} options={options.brands} /><SelectField label="Categoria" value={filters.category} onChange={(value) => updateFilter("category", value)} options={options.categories} /><SelectField label="Stagione" value={filters.season} onChange={(value) => updateFilter("season", value)} options={options.seasons} /><SelectField label="Pagamento" value={filters.paymentMethod} onChange={(value) => updateFilter("paymentMethod", value)} options={[{ value: "CASH", label: "Contanti" }, { value: "CARD", label: "Carta" }, { value: "GIFT_CARD", label: "Gift card" }, { value: "STORE_CREDIT", label: "Buono reso" }, { value: "OTHER", label: "Altro" }]} /><button className="clear-history-filters" onClick={() => setFilters(initialFilters)}>Azzera filtri</button></div>}
    {periodOpen && <div className="period-layer" role="dialog" aria-modal="true" aria-label="Seleziona periodo"><button className="period-backdrop" aria-label="Chiudi" onClick={() => setPeriodOpen(false)} /><aside className="period-drawer"><header><div><p className="eyebrow">Storico vendite</p><h3>Seleziona periodo</h3></div><button aria-label="Chiudi" onClick={() => setPeriodOpen(false)}><X size={20} /></button></header><div className="period-dates"><label><span>Data inizio</span><input type="date" value={periodDraft.dateFrom} onChange={(event) => setPeriodDraft((current) => ({ ...current, dateFrom: event.target.value, preset: "" }))} /></label><label><span>Data fine</span><input type="date" value={periodDraft.dateTo} onChange={(event) => setPeriodDraft((current) => ({ ...current, dateTo: event.target.value, preset: "" }))} /></label></div><div className="period-presets"><h4>Periodi preimpostati</h4>{[["TODAY", "Oggi"], ["YESTERDAY", "Ieri"], ["LAST_7", "Ultimi 7 giorni"], ["CURRENT_WEEK", "Settimana corrente"], ["PREVIOUS_WEEK", "Settimana scorsa"], ["CURRENT_MONTH", "Mese corrente"], ["PREVIOUS_MONTH", "Mese scorso"]].map(([value, label]) => <button key={value} className={periodDraft.preset === value ? "selected" : ""} onClick={() => setPreset(value)}><i />{label}</button>)}</div><footer><button className="secondary-action" onClick={clearPeriod}>Azzera</button><button className="primary-action" onClick={applyPeriod}>Applica filtro</button></footer></aside></div>}
    <article className="sales-list-panel"><div className="sales-list-heading"><span>Vendita</span><span>Stato</span><span>Totale</span></div>{loading && <p className="sales-empty">Caricamento vendite...</p>}{error && <p className="sales-error">{error}</p>}{!loading && !error && !sales.length && <p className="sales-empty">Nessuna vendita corrisponde ai filtri scelti.</p>}{sales.map((sale) => <button className="sales-list-row sales-record" key={sale.id} disabled={sale.status !== "CONFIRMED"} title={sale.status === "CONFIRMED" ? "Apri vendita e avvia un reso" : "Un reso richiede una vendita conclusa"} onClick={() => onStartReturn?.(sale)}><div><strong>{sale.number || "Bozza senza numero"}</strong><span>{sale.customer_name || "Vendita banco"} · {dateFormatter.format(new Date(sale.confirmed_at || sale.opened_at))}</span></div><span className={`status-pill ${sale.status.toLowerCase()}`}>{sale.status === "CONFIRMED" ? "Conclusa" : sale.status === "CANCELLED" ? "Annullata" : "Aperta"}</span><strong>{euro.format(Number(sale.final_total_amount))}</strong></button>)}</article><div className="sales-count"><ShoppingBag size={16} /> {sales.length} vendite visualizzate</div>
  </section>;
}
