import { useEffect, useState } from "react";
import { Building2, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { request } from "../api";
import "../products.css";

const list = (data) => data?.results || data || [];
const emptyForm = { code: "", business_name: "", vat_number: "", tax_code: "", sdi_code: "", pec: "", email: "", phone: "", website: "", address: "", postal_code: "", city: "", province: "", country_code: "IT", payment_terms: "", notes: "", is_active: true };

export default function SuppliersPage() {
  const [suppliers, setSuppliers] = useState([]); const [query, setQuery] = useState(""); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false);
  const load = async (search = query) => { try { setSuppliers(list(await request(`/suppliers/suppliers/?search=${encodeURIComponent(search)}`))); } catch (error) { setSuccess(false); setMessage(error.message); } };
  useEffect(() => { load(""); }, []);
  useEffect(() => { if (!message) return undefined; const timer = setTimeout(() => setMessage(""), 4000); return () => clearTimeout(timer); }, [message]);
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const openCreate = () => { setEditing(null); setForm({ ...emptyForm, code: `FOR-${Date.now()}` }); setFormOpen(true); setMessage(""); };
  const openEdit = (supplier) => { setEditing(supplier); setForm({ ...emptyForm, ...supplier }); setFormOpen(true); setMessage(""); };
  async function save(event) { event.preventDefault(); setSaving(true); setMessage(""); try { await request(editing ? `/suppliers/suppliers/${editing.id}/` : "/suppliers/suppliers/", { method: editing ? "PATCH" : "POST", body: JSON.stringify(form) }); setFormOpen(false); setSuccess(true); setMessage(editing ? "Fornitore modificato correttamente." : "Fornitore creato correttamente."); await load(""); } catch (error) { setSuccess(false); setMessage(error.message); } finally { setSaving(false); } }
  async function remove(supplier) { try { await request(`/suppliers/suppliers/${supplier.id}/`, { method: "DELETE" }); setSuccess(true); setMessage("Fornitore eliminato correttamente."); await load(); } catch (error) { setSuccess(false); setMessage(error.message); } }
  return <section className="products-page suppliers-page">
    <style>{`.supplier-form{display:grid;grid-template-columns:1.25fr repeat(3,minmax(130px,1fr));gap:14px;align-items:end;padding:20px;border-radius:14px;background:#fff;box-shadow:0 7px 22px #25171a09}.supplier-form label{display:grid;gap:6px;font-size:11px;font-weight:900}.supplier-form input,.supplier-form select{box-sizing:border-box;width:100%;height:42px;border:1px solid #ded9db;border-radius:8px;padding:0 10px;background:#fff;font:inherit}.supplier-form .supplier-copy{grid-row:span 2}.supplier-form .supplier-notes{grid-column:2/4}.supplier-heading,.supplier-row{display:grid;grid-template-columns:minmax(200px,1.2fr) minmax(170px,.9fr) minmax(120px,.6fr) 110px 92px;align-items:center;gap:18px;padding:15px 22px}.supplier-heading{color:#8b858a;font-size:10px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}.supplier-row{border-top:1px solid #eeeaea}.supplier-row>div{display:grid;gap:4px}.supplier-row strong{font-size:13px}.supplier-row span{color:#817b80;font-size:12px}.supplier-row>b{font-size:12px}.supplier-status{justify-self:start;padding:5px 8px;border-radius:7px;background:#edf9f1;color:#167444;font-size:10px;font-weight:900}.supplier-status.inactive{background:#f1eff0;color:#625b60}@media(max-width:900px){.supplier-form{grid-template-columns:1fr 1fr}.supplier-form .supplier-copy{grid-column:1/-1;grid-row:auto}.supplier-form .supplier-notes{grid-column:auto}}@media(max-width:640px){.supplier-form{grid-template-columns:1fr}.supplier-heading{display:none}.supplier-row{grid-template-columns:1fr auto;padding:16px}.supplier-row>span,.supplier-row>b{display:none}.supplier-status{grid-column:2;grid-row:1}.supplier-row .customer-actions{grid-column:2;grid-row:2}.supplier-form .inline-form-actions button{flex:1}}`}</style>
    <div className="page-title-row"><div><p className="eyebrow">Acquisti</p><h2>Fornitori</h2><span>Anagrafica, contatti, dati fiscali e condizioni di pagamento dei fornitori.</span></div><button className="primary-action" onClick={openCreate}><Plus size={17} /> Nuovo fornitore</button></div>
    {formOpen && <form className="supplier-form" onSubmit={save}><div className="inventory-form-copy supplier-copy"><p className="eyebrow">{editing ? "Modifica fornitore" : "Nuovo fornitore"}</p><h3>{editing ? "Aggiorna l'anagrafica" : "Registra un fornitore"}</h3><span>La partita IVA e il codice fiscale vengono controllati per evitare duplicati.</span></div><label>Codice fornitore<input required value={form.code} onChange={(event) => update("code", event.target.value)} /></label><label>Ragione sociale<input required value={form.business_name} onChange={(event) => update("business_name", event.target.value)} /></label><label>Partita IVA<input value={form.vat_number} onChange={(event) => update("vat_number", event.target.value)} /></label><label>Codice fiscale<input value={form.tax_code} onChange={(event) => update("tax_code", event.target.value)} /></label><label>Codice SDI<input maxLength="7" value={form.sdi_code} onChange={(event) => update("sdi_code", event.target.value)} /></label><label>PEC<input type="email" value={form.pec} onChange={(event) => update("pec", event.target.value)} /></label><label>Email<input type="email" value={form.email} onChange={(event) => update("email", event.target.value)} /></label><label>Telefono<input value={form.phone} onChange={(event) => update("phone", event.target.value)} /></label><label>Indirizzo<input value={form.address} onChange={(event) => update("address", event.target.value)} /></label><label>CAP<input value={form.postal_code} onChange={(event) => update("postal_code", event.target.value)} /></label><label>Città<input value={form.city} onChange={(event) => update("city", event.target.value)} /></label><label>Provincia<input value={form.province} onChange={(event) => update("province", event.target.value)} /></label><label>Termini di pagamento<input value={form.payment_terms} onChange={(event) => update("payment_terms", event.target.value)} placeholder="Es. 30 giorni data fattura" /></label><label>Stato<select value={String(form.is_active)} onChange={(event) => update("is_active", event.target.value === "true")}><option value="true">Attivo</option><option value="false">Inattivo</option></select></label><label className="supplier-notes">Note<input value={form.notes} onChange={(event) => update("notes", event.target.value)} placeholder="Facoltative" /></label><div className="inline-form-actions"><button type="button" className="secondary-action" onClick={() => setFormOpen(false)}>Annulla</button><button className="primary-action" disabled={saving}>{saving ? "Salvataggio..." : editing ? "Salva modifiche" : "Crea fornitore"}</button></div></form>}
    {message && <p className={success ? "operation-success" : "catalog-error"}>{message}</p>}
    <form className="products-search" onSubmit={(event) => { event.preventDefault(); load(); }}><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cerca codice, ragione sociale, partita IVA, email o telefono" /><button>Ricerca</button></form>
    <article className="products-list"><div className="supplier-heading"><span>Fornitore</span><span>Contatti</span><span>Città</span><span>Stato</span><span>Azioni</span></div>{!suppliers.length ? <div className="empty-product-state"><Building2 size={28} /><strong>Nessun fornitore trovato</strong><span>Registra un fornitore per associare articoli, riordini e fatture.</span></div> : suppliers.map((supplier) => <div className="supplier-row" key={supplier.id}><div><strong>{supplier.business_name}</strong><span>{supplier.code}{supplier.vat_number ? ` · P. IVA ${supplier.vat_number}` : ""}</span></div><span>{supplier.phone || supplier.email || supplier.pec || "Nessun contatto"}</span><b>{[supplier.city, supplier.province].filter(Boolean).join(" · ") || "Non indicata"}</b><em className={supplier.is_active ? "supplier-status" : "supplier-status inactive"}>{supplier.is_active ? "Attivo" : "Inattivo"}</em><div className="customer-actions"><button title="Modifica fornitore" onClick={() => openEdit(supplier)}><Pencil size={16} /></button><button title="Elimina fornitore" onClick={() => remove(supplier)}><Trash2 size={16} /></button></div></div>)}</article>
  </section>;
}
