import { useEffect, useState } from "react";
import { Download, Plus, Search, Ticket, Trash2, X } from "lucide-react";
import { request } from "../api";
import "../products.css";

const list = (data) => data?.results || data || [];
const euro = new Intl.NumberFormat("it-IT", { style: "currency", currency: "EUR" });
const dateFormat = new Intl.DateTimeFormat("it-IT", { dateStyle: "medium" });
const emptyForm = { initial_amount: "", holder_first_name: "", holder_last_name: "", expires_at: "", notifications_enabled: false, notes: "" };
const typeLabel = { GIFT_CARD: "Buono regalo", RETURN_CREDIT: "Buono reso", GIFT_LIST: "Buono lista" };
const statusLabel = { ACTIVE: "Attivo", EXHAUSTED: "Esaurito", CANCELLED: "Annullato" };

export default function VoucherPage() {
  const [vouchers, setVouchers] = useState([]); const [query, setQuery] = useState(""); const [status, setStatus] = useState("ACTIVE");
  const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState(emptyForm); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [success, setSuccess] = useState(false); const [selected, setSelected] = useState([]);
  const load = async (search = query, selectedStatus = status) => { try { const params = new URLSearchParams(); if (search.trim()) params.set("search", search.trim()); if (selectedStatus !== "ALL") params.set("status", selectedStatus); setVouchers(list(await request(`/vouchers/vouchers/?${params}`))); } catch (error) { setSuccess(false); setMessage(error.message); } };
  useEffect(() => { load("", "ACTIVE"); }, []);
  useEffect(() => { if (!message) return undefined; const timer = setTimeout(() => setMessage(""), 4000); return () => clearTimeout(timer); }, [message]);
  const update = (field, value) => setForm((current) => ({ ...current, [field]: value }));
  async function issue(event) { event.preventDefault(); setSaving(true); setMessage(""); try { const payload = { voucher_type: "GIFT_CARD", initial_amount: form.initial_amount, holder_first_name: form.holder_first_name.trim(), holder_last_name: form.holder_last_name.trim(), notifications_enabled: form.notifications_enabled, notes: form.notes.trim() }; if (form.expires_at) payload.expires_at = new Date(form.expires_at).toISOString(); await request("/vouchers/vouchers/issue/", { method: "POST", body: JSON.stringify(payload) }); setForm(emptyForm); setFormOpen(false); setSuccess(true); setMessage("Buono emesso correttamente."); setStatus("ACTIVE"); await load("", "ACTIVE"); } catch (error) { setSuccess(false); setMessage(error.message); } finally { setSaving(false); } }
  const holder = (voucher) => [voucher.holder_first_name, voucher.holder_last_name].filter(Boolean).join(" ") || "Non intestato";
  const toggleSelected = (id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const toggleAll = () => setSelected(selected.length === vouchers.length ? [] : vouchers.map((voucher) => voucher.id));
  function downloadSelected() { const rows = vouchers.filter((voucher) => selected.includes(voucher.id)); const csv = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`; const content = [["Codice", "Tipo", "Intestatario", "Saldo", "Scadenza", "Stato"], ...rows.map((voucher) => [voucher.code, typeLabel[voucher.voucher_type], holder(voucher), voucher.current_balance, voucher.expires_at, statusLabel[voucher.status]])].map((row) => row.map(csv).join(",")).join("\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); link.download = "buoni.csv"; link.click(); URL.revokeObjectURL(link.href); }
  async function cancelSelected() { try { await Promise.all(selected.map((id) => request(`/vouchers/vouchers/${id}/cancel/`, { method: "POST", body: JSON.stringify({ reason: "Annullato dalla gestione buoni." }) }))); setSelected([]); setSuccess(true); setMessage("Buoni annullati correttamente."); await load(); } catch (error) { setSuccess(false); setMessage(error.message); } }
  return <section className="products-page vouchers-page">
    <style>{`.voucher-form{display:grid;grid-template-columns:1.35fr repeat(4,minmax(120px,1fr));gap:14px;align-items:end;padding:20px;border-radius:14px;background:#fff;box-shadow:0 7px 22px #25171a09}.voucher-form label{display:grid;gap:6px;font-size:11px;font-weight:900}.voucher-form input{box-sizing:border-box;width:100%;height:42px;border:1px solid #ded9db;border-radius:8px;padding:0 10px;background:#fff;font:inherit}.voucher-form .voucher-notes{grid-column:2/4}.voucher-form .inline-form-actions{grid-column:4/-1}.voucher-form label.notification-control{display:flex;align-items:center;gap:10px;min-height:42px;padding:0 12px;border:1px solid #ded9db;border-radius:8px;background:#fff;font-size:12px;cursor:pointer}.voucher-form .notification-control input{width:18px;height:18px;margin:0;padding:0;accent-color:#ed001b;cursor:pointer}.voucher-filters{display:flex;align-items:center;justify-content:space-between;gap:16px}.status-tabs{display:flex;align-items:center;gap:5px}.status-tabs button{height:34px;border:0;border-radius:7px;padding:0 10px;background:transparent;color:#777176;font-size:11px;font-weight:800;cursor:pointer}.status-tabs button.active{background:#18151a;color:#fff}.vouchers-heading,.voucher-row{display:grid;grid-template-columns:minmax(180px,1.25fr) minmax(130px,.9fr) 130px 110px 100px;align-items:center;gap:18px;padding:15px 22px}.vouchers-heading{color:#8b858a;font-size:10px;font-weight:900;letter-spacing:.07em;text-transform:uppercase}.voucher-row{border-top:1px solid #eeeaea}.voucher-row>div{display:grid;gap:4px}.voucher-row strong,.voucher-row>b{font-size:13px}.voucher-row span{color:#817b80;font-size:12px}.voucher-row>b{color:#b70018}.voucher-status{justify-self:start;padding:5px 8px;border-radius:7px;background:#edf9f1;color:#167444;font-size:10px;font-style:normal;font-weight:900}.voucher-status.exhausted{background:#f1eff0;color:#625b60}.voucher-status.cancelled{background:#fff0f2;color:#b00019}@media(max-width:1050px){.voucher-form{grid-template-columns:1fr 1fr}.voucher-form .inventory-form-copy{grid-column:1/-1}.voucher-form .voucher-notes,.voucher-form .inline-form-actions{grid-column:auto}}@media(max-width:720px){.voucher-filters{align-items:stretch;flex-direction:column}.status-tabs{overflow-x:auto;padding-bottom:2px}.vouchers-heading{display:none}.voucher-row{grid-template-columns:1fr auto;gap:9px;padding:16px}.voucher-row>span{display:none}.voucher-row>b{grid-column:2;grid-row:1}.voucher-status{grid-column:1;grid-row:2}.voucher-form{grid-template-columns:1fr}.voucher-form .voucher-notes,.voucher-form .inline-form-actions{grid-column:auto}.voucher-form .inline-form-actions button{flex:1}}`}</style>
    <style>{`.vouchers-heading,.voucher-row{grid-template-columns:34px minmax(180px,1.25fr) minmax(130px,.9fr) 130px 110px 100px}.voucher-row>div:nth-child(2){display:grid;gap:4px}@media(max-width:760px){.vouchers-heading{display:none}.voucher-row{grid-template-columns:28px 1fr auto}.voucher-row>span{display:none}.voucher-row .table-row-check{grid-column:1;grid-row:1}.voucher-row>div:nth-child(2){grid-column:2;grid-row:1}.voucher-row>b{grid-column:3;grid-row:1}.voucher-status{grid-column:2;grid-row:2}}`}</style>
    <div className="page-title-row"><div><p className="eyebrow">Clienti</p><h2>Buoni</h2><span>Crediti regalo e buoni da reso, utilizzabili anche parzialmente in cassa.</span></div><button className="primary-action" onClick={() => { setFormOpen(true); setMessage(""); }}><Plus size={17} /> Emetti buono</button></div>
    {formOpen && <form className="voucher-form" onSubmit={issue}><div className="inventory-form-copy"><p className="eyebrow">Nuovo buono</p><h3>Emetti un buono regalo</h3><span>Il codice viene generato automaticamente; potrà essere utilizzato anche in più vendite.</span></div><label>Valore iniziale<input required min="0.01" step="0.01" type="number" value={form.initial_amount} onChange={(event) => update("initial_amount", event.target.value)} placeholder="0,00" /></label><label>Nome intestatario<input value={form.holder_first_name} onChange={(event) => update("holder_first_name", event.target.value)} placeholder="Facoltativo" /></label><label>Cognome intestatario<input value={form.holder_last_name} onChange={(event) => update("holder_last_name", event.target.value)} placeholder="Facoltativo" /></label><label>Scadenza<input type="datetime-local" value={form.expires_at} onChange={(event) => update("expires_at", event.target.value)} /></label><label className="notification-control"><input type="checkbox" checked={form.notifications_enabled} onChange={(event) => update("notifications_enabled", event.target.checked)} /><span>Avvisami alla scadenza</span></label><label className="voucher-notes">Note<input value={form.notes} onChange={(event) => update("notes", event.target.value)} placeholder="Facoltative" /></label><div className="inline-form-actions"><button type="button" className="secondary-action" onClick={() => setFormOpen(false)}><X size={17} /> Annulla</button><button className="primary-action" disabled={saving}>{saving ? "Emissione..." : "Emetti buono"}</button></div></form>}
    {message && <p className={success ? "operation-success" : "catalog-error"}>{message}</p>}
    <div className="voucher-filters"><form className="products-search" onSubmit={(event) => { event.preventDefault(); load(); }}><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cerca codice, nome o cognome" /><button>Ricerca</button></form><div className="status-tabs">{[["ACTIVE", "Attivi"], ["EXHAUSTED", "Esauriti"], ["CANCELLED", "Annullati"], ["ALL", "Tutti"]].map(([value, label]) => <button type="button" className={status === value ? "active" : ""} key={value} onClick={() => { setStatus(value); load(query, value); }}>{label}</button>)}</div></div>
    {selected.length > 0 && <div className="table-selection-actions"><span>{selected.length} {selected.length === 1 ? "buono selezionato" : "buoni selezionati"}</span><button type="button" onClick={() => setSelected([])}>Deseleziona</button><button type="button" onClick={downloadSelected}><Download size={16} /> Scarica CSV</button><button type="button" className="delete-selected" onClick={cancelSelected}><Trash2 size={16} /> Annulla</button></div>}
    <article className="products-list vouchers-list"><div className="vouchers-heading"><span className="table-row-check"><input type="checkbox" aria-label="Seleziona tutti i buoni" checked={vouchers.length > 0 && selected.length === vouchers.length} onChange={toggleAll} /></span><span>Buono</span><span>Intestatario</span><span>Scadenza</span><span>Saldo</span><span>Stato</span></div>{!vouchers.length ? <div className="empty-product-state"><Ticket size={28} /><strong>Nessun buono trovato</strong><span>I buoni emessi e i crediti da reso compariranno qui.</span></div> : vouchers.map((voucher) => <div className={selected.includes(voucher.id) ? "voucher-row selected" : "voucher-row"} key={voucher.id}><span className="table-row-check"><input type="checkbox" aria-label={`Seleziona ${voucher.code}`} checked={selected.includes(voucher.id)} onChange={() => toggleSelected(voucher.id)} /></span><div><strong>{voucher.code}</strong><span>{typeLabel[voucher.voucher_type] || voucher.voucher_type} · Emesso {dateFormat.format(new Date(voucher.issued_at))}</span></div><span>{holder(voucher)}</span><span>{voucher.expires_at ? dateFormat.format(new Date(voucher.expires_at)) : "Senza scadenza"}</span><b>{euro.format(Number(voucher.current_balance))}</b><em className={`voucher-status ${voucher.status.toLowerCase()}`}>{statusLabel[voucher.status] || voucher.status}</em></div>)}</article>
  </section>;
}
