# Generated by Django 5.2.17 on 2026-09-01 21:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_productvariant_productbarcode_and_more'),
        ('core', '0003_shopsettings_voucher_validity_months'),
        ('customers', '0001_initial'),
        ('sales', '0003_salenumbersequence'),
        ('vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('list_type', models.CharField(choices=[('BIRTH', 'Lista nascita'), ('BIRTHDAY', 'Lista compleanno')], max_length=16)),
                ('mode', models.CharField(choices=[('PRODUCTS', 'Articoli'), ('CONTRIBUTIONS', 'Contributi')], max_length=16)),
                ('status', models.CharField(choices=[('OPEN', 'Aperta'), ('CLOSED', 'Chiusa'), ('CANCELLED', 'Annullata')], default='OPEN', max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('beneficiary_first_name', models.CharField(max_length=120)),
                ('beneficiary_last_name', models.CharField(max_length=120)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_gift_lists', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_gift_lists', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_gift_lists', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_lists', to='customers.customer')),
                ('generated_voucher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_gift_list', to='vouchers.voucher')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_lists', to='core.location')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GiftListContribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor_first_name', models.CharField(max_length=120)),
                ('contributor_last_name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Contanti'), ('CARD', 'Carta'), ('OTHER', 'Altro')], max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('gift_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contributions', to='giftlists.giftlist')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_gift_list_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('occurred_at', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='GiftListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_quantity', models.PositiveIntegerField(default=1)),
                ('reserved_quantity', models.PositiveIntegerField(default=1)),
                ('purchased_quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='added_gift_list_items', to=settings.AUTH_USER_MODEL)),
                ('gift_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='giftlists.giftlist')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_list_items', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='GiftListItemPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('sold_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='giftlists.giftlistitem')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_gift_list_purchases', to=settings.AUTH_USER_MODEL)),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gift_list_purchases', to='sales.saleline')),
            ],
            options={
                'ordering': ('sold_at',),
            },
        ),
        migrations.CreateModel(
            name='ReservedStockSaleAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_sale_quantity', models.PositiveIntegerField()),
                ('stock_quantity_snapshot', models.PositiveIntegerField()),
                ('reserved_quantity_snapshot', models.PositiveIntegerField()),
                ('affected_list_codes', models.JSONField(default=list)),
                ('reason', models.CharField(max_length=255)),
                ('authorized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_reserved_stock_sales', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_stock_authorizations', to='sales.sale')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserved_stock_sale_authorizations', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('-authorized_at',),
            },
        ),
        migrations.AddIndex(
            model_name='giftlist',
            index=models.Index(fields=['status', 'list_type'], name='giftlist_status_type_idx'),
        ),
        migrations.AddIndex(
            model_name='giftlist',
            index=models.Index(fields=['beneficiary_last_name', 'beneficiary_first_name'], name='giftlist_benef_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='giftlist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('list_type', 'BIRTH'), _negated=True), ('mode', 'PRODUCTS'), _connector='OR'), name='giftlist_birth_products_only'),
        ),
        migrations.AddConstraint(
            model_name='giftlist',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'CLOSED'), _negated=True), models.Q(('closed_at__isnull', False), ('closed_by__isnull', False)), _connector='OR'), name='giftlist_closed_audit'),
        ),
        migrations.AddConstraint(
            model_name='giftlistcontribution',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='giftlist_contribution_positive'),
        ),
        migrations.AddConstraint(
            model_name='giftlistitem',
            constraint=models.UniqueConstraint(fields=('gift_list', 'variant'), name='giftlist_item_variant_unique'),
        ),
        migrations.AddConstraint(
            model_name='giftlistitem',
            constraint=models.CheckConstraint(condition=models.Q(('requested_quantity__gt', 0)), name='giftlist_item_requested_pos'),
        ),
        migrations.AddConstraint(
            model_name='giftlistitem',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__lte', models.F('requested_quantity')), ('purchased_quantity__lte', models.F('requested_quantity'))), name='giftlist_item_quantities_ok'),
        ),
        migrations.AddConstraint(
            model_name='giftlistitempurchase',
            constraint=models.UniqueConstraint(fields=('item', 'sale_line'), name='giftlist_item_sale_unique'),
        ),
        migrations.AddConstraint(
            model_name='giftlistitempurchase',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='giftlist_purchase_qty_pos'),
        ),
        migrations.AddConstraint(
            model_name='reservedstocksaleauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('requested_sale_quantity__gt', 0)), name='giftlist_auth_sale_qty_pos'),
        ),
        migrations.AddConstraint(
            model_name='reservedstocksaleauthorization',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity_snapshot__gt', 0)), name='giftlist_auth_reserved_pos'),
        ),
    ]
