# Generated by Django 5.2.17 on 2026-09-01 23:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDashboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=48, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_dashboards', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_report_dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ReportWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('visualization', models.CharField(choices=[('KPI', 'Valore'), ('LINE', 'Linea'), ('BAR', 'Istogramma'), ('PIE', 'Torta'), ('TABLE', 'Tabella')], max_length=16)),
                ('metric', models.CharField(choices=[('REVENUE', 'Incassi'), ('SALES', 'Numero vendite'), ('UNITS', 'Articoli venduti'), ('DISCOUNTS', 'Sconti'), ('GROSS_MARGIN', 'Margine stimato'), ('RETURNS', 'Resi'), ('INVENTORY_VALUE', 'Valore magazzino'), ('INVENTORY_VARIANCE', 'Differenze inventariali')], max_length=32)),
                ('period', models.CharField(choices=[('TODAY', 'Oggi'), ('THIS_WEEK', 'Questa settimana'), ('THIS_MONTH', 'Questo mese'), ('LAST_30_DAYS', 'Ultimi 30 giorni'), ('THIS_YEAR', 'Anno corrente'), ('CUSTOM', 'Periodo personalizzato')], max_length=24)),
                ('group_by', models.CharField(choices=[('NONE', 'Nessuno'), ('DAY', 'Giorno'), ('WEEK', 'Settimana'), ('MONTH', 'Mese'), ('CHANNEL', 'Canale'), ('BRAND', 'Marca'), ('CATEGORY', 'Categoria'), ('PROMOTION', 'Promozione')], default='NONE', max_length=24)),
                ('custom_date_from', models.DateField(blank=True, null=True)),
                ('custom_date_to', models.DateField(blank=True, null=True)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('compare_previous_period', models.BooleanField(default=False)),
                ('auto_refresh_daily', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('width', models.PositiveSmallIntegerField(default=1)),
                ('height', models.PositiveSmallIntegerField(default=1)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_report_widgets', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reporting.reportdashboard')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_report_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('dashboard', 'position', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='ReportSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField()),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('result', models.JSONField(default=dict)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_report_snapshots', to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='reporting.reportwidget')),
            ],
            options={
                'ordering': ('-snapshot_date',),
            },
        ),
        migrations.CreateModel(
            name='ReportExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_format', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'Excel')], max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('COMPLETED', 'Completata'), ('FAILED', 'Fallita')], default='PENDING', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('error', models.TextField(blank=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_exports', to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exports', to='reporting.reportwidget')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='reportwidget',
            constraint=models.CheckConstraint(condition=models.Q(('height__gt', 0), ('width__gt', 0)), name='report_widget_dimensions_positive'),
        ),
        migrations.AddConstraint(
            model_name='reportwidget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('custom_date_from__isnull', False), ('custom_date_to__gte', models.F('custom_date_from')), ('custom_date_to__isnull', False), ('period', 'CUSTOM')), models.Q(models.Q(('period', 'CUSTOM'), _negated=True), ('custom_date_from__isnull', True), ('custom_date_to__isnull', True)), _connector='OR'), name='report_widget_custom_dates_valid'),
        ),
        migrations.AddConstraint(
            model_name='reportsnapshot',
            constraint=models.UniqueConstraint(fields=('widget', 'snapshot_date'), name='report_widget_daily_snapshot_unique'),
        ),
    ]
