# Generated by Django 5.2.17 on 2026-09-01 21:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0003_salenumbersequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('voucher_type', models.CharField(choices=[('GIFT_CARD', 'Buono regalo'), ('GIFT_LIST', 'Buono lista'), ('RETURN_CREDIT', 'Buono reso')], max_length=24)),
                ('status', models.CharField(choices=[('ACTIVE', 'Attivo'), ('EXHAUSTED', 'Esaurito'), ('CANCELLED', 'Annullato')], default='ACTIVE', max_length=16)),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('holder_first_name', models.CharField(blank=True, max_length=120)),
                ('holder_last_name', models.CharField(blank=True, max_length=120)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_vouchers', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='ExpiredVoucherAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at_snapshot', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('authorized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_expired_vouchers', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expired_voucher_authorizations', to='sales.sale')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expired_use_authorizations', to='vouchers.voucher')),
            ],
            options={
                'ordering': ('-authorized_at',),
            },
        ),
        migrations.CreateModel(
            name='VoucherExpiryChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_expires_at', models.DateTimeField()),
                ('new_expires_at', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changed_voucher_expiries', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expiry_changes', to='vouchers.voucher')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='VoucherMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('ISSUE', 'Emissione'), ('REDEMPTION', 'Utilizzo'), ('ADJUSTMENT', 'Rettifica'), ('CANCELLATION', 'Annullamento')], max_length=16)),
                ('amount_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_type', models.CharField(blank=True, max_length=64)),
                ('source_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_voucher_movements', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='vouchers.voucher')),
            ],
            options={
                'ordering': ('occurred_at', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['holder_last_name', 'holder_first_name'], name='voucher_holder_name_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['source_type', 'source_id'], name='voucher_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('initial_amount__gt', 0)), name='voucher_initial_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('current_balance__gte', 0), ('current_balance__lte', models.F('initial_amount'))), name='voucher_balance_valid'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('issued_at'))), name='voucher_expiry_valid'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'EXHAUSTED'), _negated=True), ('current_balance', Decimal('0.00')), _connector='OR'), name='voucher_exhausted_balance_zero'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'ACTIVE'), _negated=True), ('current_balance__gt', Decimal('0.00')), _connector='OR'), name='voucher_active_balance_positive'),
        ),
        migrations.AddConstraint(
            model_name='expiredvoucherauthorization',
            constraint=models.UniqueConstraint(fields=('voucher', 'sale'), name='voucher_expired_auth_sale_unique'),
        ),
        migrations.AddConstraint(
            model_name='voucherexpirychange',
            constraint=models.CheckConstraint(condition=models.Q(('new_expires_at', models.F('previous_expires_at')), _negated=True), name='voucher_expiry_change_required'),
        ),
        migrations.AddIndex(
            model_name='vouchermovement',
            index=models.Index(fields=['voucher', 'occurred_at'], name='voucher_move_date_idx'),
        ),
        migrations.AddIndex(
            model_name='vouchermovement',
            index=models.Index(fields=['source_type', 'source_id'], name='voucher_move_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='vouchermovement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_delta', 0), _negated=True), name='voucher_movement_non_zero'),
        ),
        migrations.AddConstraint(
            model_name='vouchermovement',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='voucher_movement_balance_non_negative'),
        ),
    ]
