# Generated by Django 5.2.17 on 2026-08-30 00:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_product_productvariant_productbarcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('business_name', models.CharField(max_length=160)),
                ('vat_number', models.CharField(blank=True, max_length=32)),
                ('tax_code', models.CharField(blank=True, max_length=32)),
                ('sdi_code', models.CharField(blank=True, max_length=7)),
                ('pec', models.EmailField(blank=True, max_length=254)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('website', models.URLField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(blank=True, max_length=16)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('province', models.CharField(blank=True, max_length=64)),
                ('country_code', models.CharField(default='IT', max_length=2)),
                ('payment_terms', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('business_name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('vat_number', ''), _negated=True), fields=('vat_number',), name='suppliers_vat_number_unique_when_present'), models.UniqueConstraint(condition=models.Q(('tax_code', ''), _negated=True), fields=('tax_code',), name='suppliers_tax_code_unique_when_present')],
            },
        ),
        migrations.CreateModel(
            name='SupplierVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_product_code', models.CharField(blank=True, max_length=80)),
                ('is_preferred', models.BooleanField(default=False)),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1)),
                ('lead_time_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_links', to='suppliers.supplier')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_links', to='catalog.productvariant')),
            ],
            options={
                'ordering': ('supplier', 'variant'),
                'constraints': [models.UniqueConstraint(fields=('supplier', 'variant'), name='suppliers_supplier_variant_unique'), models.UniqueConstraint(condition=models.Q(('is_preferred', True)), fields=('variant',), name='suppliers_one_preferred_supplier_per_variant'), models.CheckConstraint(condition=models.Q(('minimum_order_quantity__gte', 1)), name='suppliers_minimum_order_quantity_positive')],
            },
        ),
    ]
