# Generated by Django 5.2.17 on 2026-08-29 22:51

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('SALES_FLOOR', 'Area vendita'), ('STOCKROOM', 'Magazzino interno'), ('OTHER', 'Altro')], max_length=24)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.BooleanField(default=True, editable=False, unique=True)),
                ('shop_name', models.CharField(max_length=160)),
                ('timezone', models.CharField(default='Europe/Rome', max_length=64)),
                ('currency_code', models.CharField(default='EUR', max_length=3)),
                ('default_markup', models.DecimalField(decimal_places=3, default=Decimal('2.500'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('return_credit_months', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('price_rounding_strategy', models.CharField(choices=[('NEAREST_90', 'Finale ,90 più vicino')], default='NEAREST_90', max_length=24)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='core_single_default_tax_rate')],
            },
        ),
    ]
